begin;
select no_plan();
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values('77000000-0000-4000-8000-000000000001','00000000-0000-0000-0000-000000000000','authenticated','authenticated','phase77-1@example.invalid',now(),'{}','{}',now(),now());
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values('77000000-0000-4000-8000-000000000002','00000000-0000-0000-0000-000000000000','authenticated','authenticated','phase77-2@example.invalid',now(),'{}','{}',now(),now());
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values('77000000-0000-4000-8000-000000000003','00000000-0000-0000-0000-000000000000','authenticated','authenticated','phase77-3@example.invalid',now(),'{}','{}',now(),now());
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values('77000000-0000-4000-8000-000000000004','00000000-0000-0000-0000-000000000000','authenticated','authenticated','phase77-4@example.invalid',now(),'{}','{}',now(),now());
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values('77000000-0000-4000-8000-000000000005','00000000-0000-0000-0000-000000000000','authenticated','authenticated','phase77-5@example.invalid',now(),'{}','{}',now(),now());
insert into public.profiles(user_id,roles) values('77000000-0000-4000-8000-000000000001',array['founder']),('77000000-0000-4000-8000-000000000004',array['founder']),('77000000-0000-4000-8000-000000000005',array['advisor']) on conflict(user_id) do update set roles=excluded.roles;
insert into public.network_memberships(user_id,status) values('77000000-0000-4000-8000-000000000001','active') on conflict(user_id) do update set status='active';
insert into public.network_profiles(user_id,display_name,headline,bio,network_roles,status,published_at) values('77000000-0000-4000-8000-000000000001','Public author 1','Local security profile','A sufficiently complete biography for this isolated security test.',array['founder'],'active',now());
insert into public.network_memberships(user_id,status) values('77000000-0000-4000-8000-000000000004','active') on conflict(user_id) do update set status='active';
insert into public.network_profiles(user_id,display_name,headline,bio,network_roles,status,published_at) values('77000000-0000-4000-8000-000000000004','Public author 4','Local security profile','A sufficiently complete biography for this isolated security test.',array['founder'],'active',now());
insert into public.network_memberships(user_id,status) values('77000000-0000-4000-8000-000000000005','active') on conflict(user_id) do update set status='active';
insert into public.network_profiles(user_id,display_name,headline,bio,network_roles,status,published_at) values('77000000-0000-4000-8000-000000000005','Public author 5','Local security profile','A sufficiently complete biography for this isolated security test.',array['founder'],'active',now());
create temp table ids(key text primary key,id uuid);
grant all on ids to authenticated;
create temp table fields(value jsonb);
grant all on fields to authenticated;
insert into fields values('{"title":"Deliberate public question","description":"This deliberately written problem description contains only the material approved for publication.","author_intent":"observation","geographic_scope":"regional","locations":["Local"],"topics":["Education"],"industries":[],"visibility":"members_only","outlives_account":false,"private_entries":"SHOULD_NOT_COPY","author_user_id":"FORGED_AUTHOR","source_url":"https://private.invalid"}');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select lives_ok($q$insert into ids select 'w',public.create_problem_workspace('PRIVATE_WORKSPACE_TITLE','PRIVATE_DESCRIPTION')$q$,'Owner creates private workspace');
select lives_ok($q$insert into ids select 'second',public.create_problem_workspace('Second private room','')$q$,'Second isolated workspace');
select lives_ok($q$insert into ids select 'e',public.save_problem_workspace_entry((select id from ids where key='w'),'observation','PRIVATE_OBSERVATION','https://private.invalid/source','PRIVATE_SOURCE')$q$,'Private entry with source');
select lives_ok($q$insert into ids select 'foreignentry',public.save_problem_workspace_entry((select id from ids where key='second'),'test','OTHER_WORKSPACE_ENTRY')$q$,'Other room entry');
select is(public.get_problem_workspace_publication_preview((select id from ids where key='w'))->'problem','null'::jsonb,'New publication preview has no automatic title/description');
select is(public.get_problem_workspace_publication_preview((select id from ids where key='w'))->>'can_publish','true','Owner can preview and publish');
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),null,false)$q$,'42501',null,'Explicit preview consent required');
select lives_ok($q$insert into ids select 'problem',public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),null,true)$q$,'Owner publishes members-only version');
reset role;
select is((select title from public.network_problems where id=(select id from ids where key='problem')),'Deliberate public question','Only explicit public title copied');
select ok((select to_jsonb(p)::text not like '%PRIVATE_%' and to_jsonb(p)::text not like '%SHOULD_NOT_COPY%' and to_jsonb(p)::text not like '%private.invalid%' from public.network_problems p where id=(select id from ids where key='problem')),'No private entries, sources, metadata or invitations copied');
select is((select author_user_id from public.network_problems where id=(select id from ids where key='problem')),'77000000-0000-4000-8000-000000000001'::uuid,'Publication author always session owner');
select is((select source_problem_id from public.network_problem_workspaces where id=(select id from ids where key='w')),null::uuid,'Outgoing publication does not overwrite incoming source');
select is((select published_problem_id from public.network_problem_workspaces where id=(select id from ids where key='w')),(select id from ids where key='problem'),'Separate outgoing reference persisted');
select is((select count(*)::int from public.get_public_network_problem((select public_slug from public.network_problems where id=(select id from ids where key='problem')))),0,'Members-only version absent from anonymous public RPC');
select ok(not exists(select 1 from public.list_public_network_sitemap() where path='/connect/pr/'||(select public_slug from public.network_problems where id=(select id from ids where key='problem'))),'Members-only version absent from sitemap');
insert into public.network_problem_workspace_members(workspace_id,user_id,role) values((select id from ids where key='w'),'77000000-0000-4000-8000-000000000002','contributor'),((select id from ids where key='w'),'77000000-0000-4000-8000-000000000003','viewer');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select throws_ok($q$select public.get_problem_workspace_publication_preview((select id from ids where key='w'))$q$,'42501',null,'Contributor cannot open publish preview');
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),(select id from ids where key='problem'),true)$q$,'42501',null,'Contributor cannot publish');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'42501',null,'Contributor cannot create opportunity');
select is(public.get_problem_workspace_development((select id from ids where key='w'))->'publication','null'::jsonb,'Contributor guest receives no members-only problem link');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select throws_ok($q$select public.get_problem_workspace_publication_preview((select id from ids where key='w'))$q$,'42501',null,'Viewer cannot open publish preview');
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),(select id from ids where key='problem'),true)$q$,'42501',null,'Viewer cannot publish');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'42501',null,'Viewer cannot create opportunity');
select is(public.get_problem_workspace_development((select id from ids where key='w'))->'publication','null'::jsonb,'Viewer guest receives no members-only problem link');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select throws_ok($q$select public.get_problem_workspace_publication_preview((select id from ids where key='w'))$q$,'42501',null,'Nonmember cannot open publish preview');
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),(select id from ids where key='problem'),true)$q$,'42501',null,'Nonmember cannot publish');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'42501',null,'Nonmember cannot create opportunity');
select throws_ok($q$select public.get_problem_workspace_development((select id from ids where key='w'))$q$,'42501',null,'Nonmember cannot read opportunities');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),null,true)$q$,'42501',null,'Stale create preview cannot duplicate published problem');
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),'77000000-0000-4000-8000-000000000999'::uuid,true)$q$,'42501',null,'Manipulated publication ID denied');
update fields set value=jsonb_set(value,'{visibility}','"public"');
select lives_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),(select id from ids where key='problem'),true)$q$,'Owner deliberately updates same version to public');
reset role;
select is((select count(*)::int from public.get_public_network_problem((select public_slug from public.network_problems where id=(select id from ids where key='problem')))),1,'Public version uses existing public RPC');
select ok(exists(select 1 from public.list_public_network_sitemap() where path='/connect/pr/'||(select public_slug from public.network_problems where id=(select id from ids where key='problem'))),'Public version uses existing sitemap');
select ok((select to_jsonb(p)::text not like '%PRIVATE_%' from public.get_public_network_problem((select public_slug from public.network_problems where id=(select id from ids where key='problem'))) p),'Public read has no private workspace data');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select is(public.get_problem_workspace_development((select id from ids where key='w'))->'publication'->>'visibility','public','Guest can receive existing publicly permitted problem link');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select lives_ok($q$insert into ids select 'sourcew',public.create_problem_workspace('Source workspace','PRIVATE_SOURCE_WORKSPACE',(select id from ids where key='problem'))$q$,'Existing problem to private workspace');
select is(public.get_problem_workspace_publication_preview((select id from ids where key='sourcew'))->'problem'->>'title','Deliberate public question','Existing source publication explicitly prefills preview');
select lives_ok($q$select public.publish_problem_workspace((select id from ids where key='sourcew'),(select value from fields),(select id from ids where key='problem'),true)$q$,'Own active source updated through explicit preview');
reset role;
select is((select source_problem_id from public.network_problem_workspaces where id=(select id from ids where key='sourcew')),(select id from ids where key='problem'),'Incoming source semantics retained');
select is((select description from public.network_problem_workspaces where id=(select id from ids where key='sourcew')),'PRIVATE_SOURCE_WORKSPACE','Public update leaves private description intact');
update public.network_problems set author_user_id='77000000-0000-4000-8000-000000000004' where id=(select id from ids where key='problem');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),(select id from ids where key='problem'),true)$q$,'42501',null,'Lost problem ownership forbids update');
select throws_ok($q$select public.get_problem_workspace_publication_preview((select id from ids where key='w'))$q$,'42501',null,'Lost ownership forbids preview');
reset role;
update public.network_problems set author_user_id='77000000-0000-4000-8000-000000000001' where id=(select id from ids where key='problem');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select lives_ok($q$insert into ids select 'o',public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change',array[(select id from ids where key='e')],null)$q$,'Owner creates opportunity with explicit internal entry');
select lives_ok($q$insert into ids select 'o2',public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'Multiple opportunities in same workspace');
select lives_ok($q$insert into ids select 'o3',public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'Third opportunity');
select lives_ok($q$insert into ids select 'o4',public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'Fourth opportunity for blocking/link tests');
select is(jsonb_array_length(public.get_problem_workspace_development((select id from ids where key='w'))->'opportunities'),4,'All opportunities returned without ranking');
select lives_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change',array[(select id from ids where key='e')],(select id from ids where key='o'))$q$,'Owner edits opportunity');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='second'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',(select id from ids where key='o'))$q$,'42501',null,'Foreign workspace/opportunity pairing denied');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change',array[(select id from ids where key='foreignentry')],null)$q$,'42501',null,'Foreign workspace reference denied');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),repeat('x',161),'Group','Statement','Value')$q$,'23514',null,'Opportunity title limit');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Title','', 'Statement','Value')$q$,'23514',null,'Opportunity group required');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Title',repeat('x',501),'Statement','Value')$q$,'23514',null,'Opportunity group limit');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Title','Group',repeat('x',2001),'Value')$q$,'23514',null,'Opportunity hypothesis limit');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Title','Group','Statement',repeat('x',2001))$q$,'23514',null,'Opportunity value limit');
reset role;
select is((select created_by from public.network_problem_opportunities where id=(select id from ids where key='o')),'77000000-0000-4000-8000-000000000001'::uuid,'Opportunity author is session user');
select throws_ok($q$insert into public.network_problem_opportunity_entries values((select id from ids where key='w'),(select id from ids where key='o'),(select id from ids where key='foreignentry'))$q$,'23503',null,'Composite FK prevents cross-workspace references even in privileged writes');
select throws_ok($q$update public.network_problem_opportunities set status='ranked' where id=(select id from ids where key='o')$q$,'23514',null,'Only active/archived status');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select is(jsonb_array_length(public.get_problem_workspace_development((select id from ids where key='w'))->'opportunities'),4,'Contributor reads workspace opportunities');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',(select id from ids where key='o'))$q$,'42501',null,'Contributor cannot edit');
select throws_ok($q$select public.archive_problem_opportunity((select id from ids where key='w'),(select id from ids where key='o'))$q$,'42501',null,'Contributor cannot archive');
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o'),null,'New named venture')$q$,'42501',null,'Contributor cannot create venture');
select throws_ok($q$select public.list_problem_opportunity_ventures((select id from ids where key='w'))$q$,'42501',null,'Contributor cannot inspect owner venture choices');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select is(jsonb_array_length(public.get_problem_workspace_development((select id from ids where key='w'))->'opportunities'),4,'Viewer reads workspace opportunities');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',(select id from ids where key='o'))$q$,'42501',null,'Viewer cannot edit');
select throws_ok($q$select public.archive_problem_opportunity((select id from ids where key='w'),(select id from ids where key='o'))$q$,'42501',null,'Viewer cannot archive');
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o'),null,'New named venture')$q$,'42501',null,'Viewer cannot create venture');
select throws_ok($q$select public.list_problem_opportunity_ventures((select id from ids where key='w'))$q$,'42501',null,'Viewer cannot inspect owner venture choices');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select lives_ok($q$insert into ids select 'oldsolo',public.create_solo_venture()$q$,'Baseline canonical solo venture exists');
select lives_ok($q$insert into ids select 'newventure',public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o'),null,'New named venture')$q$,'New creates genuinely new canonical venture');
select ok((select id from ids where key='newventure') <> (select id from ids where key='oldsolo'),'New branch never silently picks oldest/newest solo venture');
select is((select count(*)::int from public.founder_team_members where team_id=(select id from ids where key='newventure')),1,'Only owner added, no workspace participants');
select is((select user_id from public.founder_team_members where team_id=(select id from ids where key='newventure')),'77000000-0000-4000-8000-000000000001'::uuid,'Owner is sole founder');
select is((select team_context from public.founder_teams where id=(select id from ids where key='newventure')),'pre_founder','Canonical solo context preserved');
select is(public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o'),null,'New named venture'),(select id from ids where key='newventure'),'Double submission returns existing linked venture');
select lives_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o2'),(select id from ids where key='oldsolo'),'New named venture')$q$,'Explicit selected existing own venture links');
select lives_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o3'),(select id from ids where key='oldsolo'),'New named venture')$q$,'Same venture may originate from multiple opportunities');
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o2'),(select id from ids where key='newventure'),'New named venture')$q$,'42501',null,'Opportunity cannot silently switch linked venture');
reset role;
insert into public.founder_teams(id,name,team_context) values('77000000-0000-4000-8000-000000000100','FOREIGN_VENTURE','pre_founder');
insert into public.founder_team_members values('77000000-0000-4000-8000-000000000100','77000000-0000-4000-8000-000000000004',now());
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o4'),'77000000-0000-4000-8000-000000000100'::uuid,'New named venture')$q$,'42501',null,'Cannot link foreign venture');
select ok(public.list_problem_opportunity_ventures((select id from ids where key='w'))::text not like '%FOREIGN_VENTURE%','Chooser contains no foreign venture');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select is(public.get_problem_workspace_development((select id from ids where key='w'))->'opportunities'->0->'venture','null'::jsonb,'Viewer gets no team name or ID without existing team membership');
select is((select count(*)::int from public.founder_teams where id=(select id from ids where key='newventure')),0,'Workspace grant does not extend founder-team RLS');
reset role;
insert into public.founder_team_members(team_id,user_id) values((select id from ids where key='oldsolo'),'77000000-0000-4000-8000-000000000002'),((select id from ids where key='oldsolo'),'77000000-0000-4000-8000-000000000003');
select throws_ok($q$insert into public.founder_team_members(team_id,user_id) values((select id from ids where key='oldsolo'),'77000000-0000-4000-8000-000000000004')$q$,'23514',null,'Existing three-founder limit unchanged');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select ok(public.get_problem_workspace_development((select id from ids where key='w'))::text like '%'||(select id from ids where key='oldsolo')||'%','Already authorized founder may receive own venture link');
reset role;
insert into public.network_blocks(blocker_user_id,blocked_user_id) values('77000000-0000-4000-8000-000000000001','77000000-0000-4000-8000-000000000002');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o4'),(select id from ids where key='oldsolo'),'New named venture')$q$,'42501',null,'Block prevents linking existing team with blocked founder');
select ok(public.list_problem_opportunity_ventures((select id from ids where key='w'))::text not like '%'||(select id from ids where key='oldsolo')||'%','Blocked team removed from chooser');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select throws_ok($q$select public.get_problem_workspace_development((select id from ids where key='w'))$q$,'42501',null,'Blocked workspace member loses opportunity reads');
reset role;
delete from public.network_blocks where blocker_user_id='77000000-0000-4000-8000-000000000001';
insert into public.network_blocks(blocker_user_id,blocked_user_id) values('77000000-0000-4000-8000-000000000002','77000000-0000-4000-8000-000000000001');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o4'),(select id from ids where key='oldsolo'),'New named venture')$q$,'42501',null,'Reverse block also prevents team link');
reset role;
delete from public.network_blocks where blocker_user_id='77000000-0000-4000-8000-000000000002';
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000005',true);
set local role authenticated;
select lives_ok($q$insert into ids select 'nofounder',public.create_problem_workspace('Network only','')$q$,'CONNECT-only owner workspace');
select lives_ok($q$insert into ids select 'nofounderopp',public.save_problem_opportunity((select id from ids where key='nofounder'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'CONNECT-only owner opportunity');
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='nofounder'),(select id from ids where key='nofounderopp'),null,'Unauthorized founder role')$q$,'42501',null,'No implicit founder entitlement');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select lives_ok($q$select public.archive_problem_opportunity((select id from ids where key='w'),(select id from ids where key='o2'))$q$,'Owner archives opportunity');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',(select id from ids where key='o2'))$q$,'42501',null,'Archived opportunity cannot be edited');
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o2'),null,'New named venture')$q$,'42501',null,'Archived opportunity cannot create or link');
select is((select count(*)::int from public.founder_teams where id=(select id from ids where key='oldsolo')),1,'Opportunity archive preserves linked venture');
select lives_ok($q$select public.set_problem_workspace_member((select id from ids where key='w'),'77000000-0000-4000-8000-000000000003','remove')$q$,'Remove viewer');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select throws_ok($q$select public.get_problem_workspace_development((select id from ids where key='w'))$q$,'42501',null,'Removed member loses all new reads');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($q$select * from public.network_problem_opportunities$q$,'42501',null,'No direct authenticated read: network_problem_opportunities');
select throws_ok($q$delete from public.network_problem_opportunities$q$,'42501',null,'No direct authenticated writes: network_problem_opportunities');
select throws_ok($q$select * from public.network_problem_opportunity_entries$q$,'42501',null,'No direct authenticated read: network_problem_opportunity_entries');
select throws_ok($q$delete from public.network_problem_opportunity_entries$q$,'42501',null,'No direct authenticated writes: network_problem_opportunity_entries');
select throws_ok($q$select public.can_access_opportunity_venture((select id from ids where key='oldsolo'))$q$,'42501',null,'Internal helper not callable by clients');
select lives_ok($q$select public.archive_problem_workspace((select id from ids where key='w'))$q$,'Archive workspace');
select lives_ok($q$select public.get_problem_workspace_development((select id from ids where key='w'))$q$,'Archived workspace remains authorized read-only');
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),(select id from ids where key='problem'),true)$q$,'42501',null,'Archived workspace cannot publish');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'42501',null,'Archived workspace cannot create opportunity');
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o4'),(select id from ids where key='oldsolo'),'New named venture')$q$,'42501',null,'Archived workspace cannot link venture');
select is((select status from public.network_problems where id=(select id from ids where key='problem')),'active','Workspace archive never withdraws published problem');
reset role;
select set_config('request.jwt.claim.sub','',true);
set local role anon;
select throws_ok($q$select public.get_problem_workspace_development((select id from ids where key='w'))$q$,'42501',null,'Anonymous new RPC denied');
select throws_ok($q$select public.get_problem_workspace_publication_preview((select id from ids where key='w'))$q$,'42501',null,'Anonymous new RPC denied');
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='w'),(select value from fields),null,true)$q$,'42501',null,'Anonymous new RPC denied');
select throws_ok($q$select public.save_problem_opportunity((select id from ids where key='w'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change','{}',null)$q$,'42501',null,'Anonymous new RPC denied');
select throws_ok($q$select public.link_problem_opportunity_venture((select id from ids where key='w'),(select id from ids where key='o'),null,'New named venture')$q$,'42501',null,'Anonymous new RPC denied');
select throws_ok($q$select * from public.network_problem_opportunities$q$,'42501',null,'Anon has no opportunity table access');
reset role;
update public.network_profiles set status='paused' where user_id='77000000-0000-4000-8000-000000000001';
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='second'),(select value from fields),null,true)$q$,'23514',null,'Publication still requires existing active profile');
reset role;
update public.network_profiles set status='active' where user_id='77000000-0000-4000-8000-000000000001';
update public.network_problems set status='withdrawn' where id=(select id from ids where key='problem');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($q$select public.publish_problem_workspace((select id from ids where key='sourcew'),(select value from fields),(select id from ids where key='problem'),true)$q$,'42501',null,'Does not restore withdrawn problems through workspace');
reset role;
update public.network_problems set status='active' where id=(select id from ids where key='problem');
reset role;
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select lives_ok($q$insert into ids select 'refopp',public.save_problem_opportunity((select id from ids where key='second'),'Opportunity title','Affected group','A hypothesis about relevance','A possible valuable change',array[(select id from ids where key='foreignentry')],null)$q$,'Reference test opportunity');
select lives_ok($q$select public.delete_problem_workspace_entry((select id from ids where key='second'),(select id from ids where key='foreignentry'))$q$,'Delete original referenced entry');
select is(public.get_problem_workspace_development((select id from ids where key='second'))->'opportunities'->0->'entry_ids','[]'::jsonb,'Deleted entry disappears from reference list');
reset role;
insert into public.founder_team_members(team_id,user_id) values((select id from ids where key='newventure'),'77000000-0000-4000-8000-000000000004');
reset role;
delete from public.network_problem_workspaces where id=(select id from ids where key='w');
select is((select count(*)::int from public.network_problem_opportunities where workspace_id=(select id from ids where key='w')),0,'Workspace deletion cascades private opportunities');
select is((select count(*)::int from public.network_problems where id=(select id from ids where key='problem')),1,'Workspace deletion preserves public problem');
select is((select count(*)::int from public.founder_teams where id=(select id from ids where key='newventure')),1,'Workspace deletion preserves canonical venture');
reset role;
delete from auth.users where id='77000000-0000-4000-8000-000000000001';
select is((select count(*)::int from public.network_problem_workspaces where owner_user_id='77000000-0000-4000-8000-000000000001'),0,'Account deletion removes private owner workspaces');
select is((select count(*)::int from public.network_problem_opportunities where created_by='77000000-0000-4000-8000-000000000001'),0,'Account deletion removes private opportunities');
select is((select count(*)::int from public.founder_teams where id=(select id from ids where key='newventure')),1,'Account deletion does not cascade into team with remaining founder');
select is((select author_user_id from public.network_problems where id=(select id from ids where key='problem')),null::uuid,'No workspace FK cascades to anonymized public problem');
select * from finish();
rollback;
