\set ON_ERROR_STOP on
begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at) values
 ('78000000-0000-4000-8000-000000000001','00000000-0000-0000-0000-000000000000','authenticated','authenticated','radar-admin@example.invalid',now(),now(),now()),
 ('78000000-0000-4000-8000-000000000002','00000000-0000-0000-0000-000000000000','authenticated','authenticated','radar-user@example.invalid',now(),now(),now());
insert into public.platform_admins(user_id) values('78000000-0000-4000-8000-000000000001');
insert into public.network_problem_workspaces(id,owner_user_id,title,description) values('78000000-0000-4000-8000-000000000002','78000000-0000-4000-8000-000000000002','Private nonadmin workspace','Not accessible to radar admin');
create function pg_temp.src() returns jsonb language sql as $$ select '{"name":"Synthetic issues","domain":"fixture.invalid","allowed_path":"/issues","source_type":"public_repository_issues","retrieval_method":"manual_url","is_public":true,"source_language":"de","region":"unknown","target_context":"Small software teams","source_nature":"direct","source_origin":"primary","policy_references":"Synthetic policy fixture only","review_note":"Synthetic test permission; not an actual source approval"}'::jsonb $$;
create function pg_temp.sid() returns uuid language sql as $$select current_setting('test.radar_source')::uuid$$;
create function pg_temp.source() returns jsonb language sql as $$select s from jsonb_array_elements(public.list_radar_sources())s where s->>'id'=pg_temp.sid()::text$$;
create function pg_temp.rid() returns uuid language sql as $$select current_setting('test.radar_signal')::uuid$$;
create function pg_temp.sig() returns jsonb language sql as $$select jsonb_build_object('source_id',pg_temp.sid(),'source_url','https://fixture.invalid/issues/1?view=full&utm_source=test#top','source_title',null,'source_date',null,'source_language','de','summary_language','en','summary','Small teams repeat data entry.','problem_observation','Copying records across two tools takes time.','affected_context','Small software teams','tags',jsonb_build_array('workflow'),'sensitivity','clear','availability','unchecked')$$;
create function pg_temp.rev() returns integer language sql as $$select (public.list_radar_signals(p_id=>pg_temp.rid())->0->>'revision')::int$$;
create function pg_temp.srev() returns integer language sql as $$select (s->>'revision')::int from jsonb_array_elements(public.list_radar_sources())s where s->>'id'=pg_temp.sid()::text$$;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"78000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select extensions.throws_ok($$select public.list_radar_sources()$$,'42501','platform_admin_required','Normal user cannot read sources');
select extensions.throws_ok($$select public.list_radar_signals()$$,'42501','platform_admin_required','Normal user cannot read signals');
select extensions.throws_ok($$select public.save_radar_source(null,null,pg_temp.src())$$,'42501','platform_admin_required','Normal user cannot create source');
select extensions.throws_ok($$select public.purge_radar_expired()$$,'42501','platform_admin_required','Normal user cannot purge');
select extensions.throws_ok($$select public.save_radar_signal(null,null,'{}')$$,'42501','platform_admin_required','Normal user cannot write signals');
select extensions.throws_ok($$select public.review_radar_signal('78000000-0000-4000-8000-000000000001',1,'relevant')$$,'42501','platform_admin_required','Normal user cannot review');
select set_config('request.jwt.claims','{"sub":"78000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select extensions.throws_ok($$select * from public.radar_sources$$,'42501',null,'Admin cannot directly read raw table');
select extensions.throws_ok($$update public.radar_signals set review_status='relevant'$$,'42501',null,'Admin cannot directly write raw table');
select extensions.throws_ok($$select public.radar_normalize_url('https://fixture.invalid')$$,'42501',null,'Helper is not a client API');
select set_config('test.radar_source',public.save_radar_source(null,null,pg_temp.src())::text,true);
select extensions.is(pg_temp.source()->>'permission_state','pending','Source begins pending');
select extensions.is(pg_temp.source()->>'status','paused','Source begins paused');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig())$$,'23514','radar_source_unavailable','Pending source rejected');
select extensions.throws_ok($$select public.review_radar_source(pg_temp.sid(),pg_temp.srev(),'approved','active',now()-interval '1 day')$$,'23514','radar_approval_incomplete','Expired approval rejected');
select extensions.lives_ok($$select public.review_radar_source(pg_temp.sid(),pg_temp.srev(),'approved','active',now()+interval '90 days')$$,'Admin approves own synthetic source');
select extensions.is(pg_temp.source()->>'usable','true','Approved active manual source usable');
select extensions.throws_ok($$select public.get_problem_workspace('78000000-0000-4000-8000-000000000002')$$,'42501','workspace_forbidden','Radar admin grants no foreign workspace access');
reset role;
update public.radar_sources set review_due_at=now()-interval '1 second' where id=pg_temp.sid();
set local role authenticated;
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig())$$,'23514','radar_source_unavailable','Expired source cannot ingest');
reset role;
update public.radar_sources set review_due_at=now()+interval '90 days',retrieval_method='rss' where id=pg_temp.sid();
set local role authenticated;
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig())$$,'23514','radar_source_unavailable','Stored RSS method cannot execute manual ingest');
reset role;
update public.radar_sources set retrieval_method='manual_url' where id=pg_temp.sid();
set local role authenticated;

select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"created_by":"78000000-0000-4000-8000-000000000002"}')$$,'23514','radar_field_invalid','Actor spoof rejected');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"excerpt":"copy"}')$$,'23514','radar_field_invalid','No excerpt API');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://other.invalid/issues/1"}')$$,'23514','radar_scope_invalid','Wrong domain rejected');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://fixture.invalid/issues-foreign/1"}')$$,'23514','radar_scope_invalid','Path boundary enforced');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://fixture.invalid/issues/%2e%2e/private"}')$$,'23514','radar_url_invalid','Encoded dot scope escape rejected');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"javascript:alert(1)"}')$$,'23514','radar_url_invalid','Non-http rejected');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://user:secret@fixture.invalid/issues/1"}')$$,'23514','radar_url_invalid','Credentials rejected');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"sensitivity":"sensitive"}')$$,'23514','radar_sensitive_input','Known sensitive material never ingested');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||jsonb_build_object('summary',repeat('x',801)))$$,'23514',null,'Summary length enforced by DB');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig()||'{"source_language":"fr"}')$$,'23514',null,'Only DE/EN pilot content');
select set_config('test.radar_signal',(public.save_radar_signal(null,null,pg_temp.sig())->>'id'),true);
select extensions.is(public.list_radar_signals(p_source=>pg_temp.sid())->0->>'source_url','https://fixture.invalid/issues/1?view=full','Canonical URL removes tracking and fragment only');
select extensions.is(public.list_radar_signals(p_source=>pg_temp.sid())->0->>'source_region','unknown','Unknown region retained');
select extensions.ok(public.list_radar_signals(p_source=>pg_temp.sid())->0->>'source_date' is null,'Unknown source date retained');
select extensions.is(public.list_radar_signals(p_source=>pg_temp.sid())->0->>'created_by','78000000-0000-4000-8000-000000000001','Author derived from session');
select extensions.is(public.save_radar_signal(null,null,pg_temp.sig())->>'duplicate','true','Exact duplicate returns existing row');
select extensions.is(public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://FIXTURE.invalid:443/issues/1?utm_campaign=other&view=full&gclid=x"}')->>'id',pg_temp.rid()::text,'Tracking variation is same identity');
select extensions.is(public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://fixture.invalid/issues/1?view=compact"}')->>'duplicate','false','Content query retained');
select extensions.is(public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://fixture.invalid/issues/2","stable_public_item_id":"issue-2"}')->>'duplicate','false','Stable item created');
select extensions.is(public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://fixture.invalid/issues/renamed","stable_public_item_id":"issue-2"}')->>'duplicate','true','Stable item dedup across URLs');
select extensions.is(public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://fixture.invalid/issues/2","stable_public_item_id":"issue-3"}')->>'duplicate','false','Different stable items may share a collection URL');
select extensions.is(public.save_radar_signal(null,null,pg_temp.sig()||'{"source_url":"https://fixture.invalid/issues/2"}')->>'duplicate','true','URL-only retry cannot bypass existing item identity');

select extensions.throws_ok($$select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'relevant')$$,'23514','radar_review_required','Cannot skip reviewed state');
select extensions.lives_ok($$select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'reviewed')$$,'New to reviewed');
select extensions.lives_ok($$select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'relevant')$$,'Own fund can become relevant');
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'usable','true','Relevant signal usable');
select extensions.is((public.list_radar_signals(p_id=>pg_temp.rid())->0->>'review_due_at')::timestamptz,now()+interval '180 days','Relevant review due in 180 days');
reset role;
update public.radar_signals set review_due_at=now()-interval '1 second' where id=pg_temp.rid();
set local role authenticated;
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'usable','false','Overdue relevant cannot be used');
select public.save_radar_signal(null,null,pg_temp.sig());
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'overdue','true','Duplicate does not extend review deadline');
select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'relevant');
select extensions.throws_ok($$select public.review_radar_signal(pg_temp.rid(),1,'discarded')$$,'40001','radar_conflict','Stale concurrent action rejected');
select extensions.throws_ok($$select public.review_radar_signal(pg_temp.sid(),1,'discarded')$$,'40001','radar_conflict','Source ID cannot read/mutate another kind');
select public.save_radar_signal(pg_temp.rid(),pg_temp.rev(),pg_temp.sig()||'{"summary":"Changed own observation"}');
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'review_status','new','Edit invalidates approval');
select extensions.ok(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'reviewed_by' is null,'Edit clears reviewer');
select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'reviewed');
select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'relevant');
select public.review_radar_source(pg_temp.sid(),pg_temp.srev(),'approved','paused',now()+interval '90 days');
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'usable','false','Source pause stops existing signal use');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig())$$,'23514','radar_source_unavailable','Pause blocks retry');
select public.review_radar_source(pg_temp.sid(),pg_temp.srev(),'approved','active',now()+interval '90 days');
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'usable','false','Reactivation never silently reapproves signal');
select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'relevant');
select public.review_radar_source(pg_temp.sid(),pg_temp.srev(),'denied','withdrawn',null);
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'usable','false','Denied withdrawn source immediately blocks');
select extensions.throws_ok($$select public.save_radar_signal(null,null,pg_temp.sig())$$,'23514','radar_source_unavailable','Withdrawn/denied cannot ingest');
select public.save_radar_source(pg_temp.sid(),pg_temp.srev(),pg_temp.src()||'{"allowed_path":"/"}');
select extensions.is(pg_temp.source()->>'permission_state','pending','Scope change resets approval');
select extensions.is(pg_temp.source()->>'status','paused','Scope change never autoactivates');
select public.review_radar_source(pg_temp.sid(),pg_temp.srev(),'approved','active',now()+interval '90 days');
select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'relevant');
select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'unblocked');
select extensions.ok((public.list_radar_signals(p_id=>pg_temp.rid())->0->>'delete_after')::timestamptz<=now()+interval '30 days','Any return to unreviewed state has finite retention');
select public.save_radar_source(pg_temp.sid(),pg_temp.srev(),pg_temp.src()||'{"allowed_path":"/narrower"}');
select public.review_radar_source(pg_temp.sid(),pg_temp.srev(),'approved','active',now()+interval '90 days');
select extensions.throws_ok($$select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'reviewed')$$,'23514','radar_scope_invalid','Re-review cannot bypass changed source path');
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'usable','false','Old out-of-scope signal remains unusable');
select public.save_radar_source(pg_temp.sid(),pg_temp.srev(),pg_temp.src()||'{"allowed_path":"/"}');
select public.review_radar_source(pg_temp.sid(),pg_temp.srev(),'approved','active',now()+interval '90 days');
select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'blocked','sensitive');
select extensions.is(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'sensitivity','sensitive','Sensitive flag retained for operator');
select extensions.throws_ok($$select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'relevant')$$,'23514','radar_signal_locked','Blocked signal cannot be approved');
select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'discarded','takedown');
select extensions.ok(public.list_radar_signals(p_id=>pg_temp.rid())->0->>'summary' is null and public.list_radar_signals(p_id=>pg_temp.rid())->0->>'source_url' is null,'Discard immediately removes text and URL');
select extensions.is(public.save_radar_signal(null,null,pg_temp.sig())->>'id',pg_temp.rid()::text,'Tombstone prevents recreation');
select extensions.throws_ok($$select public.review_radar_signal(pg_temp.rid(),pg_temp.rev(),'unblocked')$$,'23514','radar_signal_locked','Discard irreversible');
select extensions.is(jsonb_array_length(public.list_radar_signals(p_status=>'discarded',p_source=>pg_temp.sid())),1,'Status filter');
select extensions.is(jsonb_array_length(public.list_radar_signals(p_language=>'en',p_source=>pg_temp.sid())),0,'Language filter');
select extensions.throws_ok($$select public.list_radar_signals(p_offset=>-1)$$,'23514','radar_filter_invalid','Bounded pagination');
reset role;
select extensions.ok(not exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name like 'radar_%' and grantee in ('PUBLIC','anon','authenticated')),'No direct table privileges including TRUNCATE');
select extensions.ok(not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('radar_sources','radar_signals','radar_review_events') and not c.relrowsecurity),'RLS on every radar table');
select extensions.ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like '%radar%' and p.prosecdef and p.proconfig is distinct from array['search_path=""']),'Definer functions use empty search_path');
select extensions.ok(exists(select 1 from public.radar_review_events where signal_id=pg_temp.rid() and actor='78000000-0000-4000-8000-000000000001' and action='discarded'),'Event actor/action/revision captured');
select extensions.is((select count(*) from information_schema.columns where table_schema='public' and table_name='radar_review_events' and column_name in ('summary','content','source_url')),0::bigint,'No full-text audit archive');
update public.radar_signals set delete_after=now()-interval '1 day',review_due_at=now()-interval '1 day' where source_id=pg_temp.sid();
set local role authenticated;
select extensions.ok(not exists(select 1 from jsonb_array_elements(public.list_radar_signals(p_source=>pg_temp.sid()))r where r->>'source_url' is not null or r->>'summary' is not null),'Expired unreviewed content masked even before cleanup');
select extensions.is(public.purge_radar_expired(),4,'Manual cleanup deletes due rows');
select extensions.is(jsonb_array_length(public.list_radar_signals(p_source=>pg_temp.sid())),0,'No indefinite unreviewed archive after cleanup');
reset role;
select extensions.is((select count(*) from public.radar_review_events where signal_id is not null and actor='78000000-0000-4000-8000-000000000001'),0::bigint,'Signal deletion cascades minimal events');
-- Live permission checks, not JWT claims or UI-only guards.
delete from public.platform_admins where user_id='78000000-0000-4000-8000-000000000001';
set local role authenticated;
select extensions.throws_ok($$select public.list_radar_sources()$$,'42501','platform_admin_required','Revocation applies next read');
select extensions.throws_ok($$select public.review_radar_source(pg_temp.sid(),1,'denied','withdrawn',null)$$,'42501','platform_admin_required','Revocation applies next write');
reset role;
set local role anon;
select set_config('request.jwt.claims','{}',true);
select extensions.throws_ok($$select public.list_radar_sources()$$,'42501',null,'Anonymous RPC forbidden');
select extensions.throws_ok($$select public.list_radar_signals()$$,'42501',null,'Anonymous signal RPC forbidden');
select extensions.throws_ok($$select * from public.radar_signals$$,'42501',null,'Anonymous raw table forbidden');
reset role;
select * from extensions.finish();
rollback;
