\set ON_ERROR_STOP on
begin;
select no_plan();
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at)
select ('78c00000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','radar-c-'||n||'@example.invalid',now(),now(),now() from generate_series(1,3)n;
insert into public.platform_admins(user_id) values('78c00000-0000-4000-8000-000000000001'),('78c00000-0000-4000-8000-000000000003');
insert into public.network_memberships(user_id,status) values('78c00000-0000-4000-8000-000000000001','active') on conflict(user_id) do update set status='active';
insert into public.network_profiles(user_id,display_name,headline,bio,network_roles,status,published_at) values('78c00000-0000-4000-8000-000000000001','Synthetic radar owner','Local security fixture','A sufficiently complete biography for the isolated radar security test.',array['founder'],'active',now());
create temp table ids(k text primary key,id uuid); grant all on ids to authenticated;
create function pg_temp.id(k text) returns uuid language sql as $$select id from ids where ids.k=$1$$;
create function pg_temp.hrev() returns int language sql as $$select (public.get_radar_hypothesis(pg_temp.id('h'))->>'revision')::int$$;
create function pg_temp.input() returns jsonb language sql as $$select '{"title":"Repeated coordination effort","problem_statement":"Small software teams may repeat coordination across tools.","affected_context":"Small software teams","hypothesis_language":"en","open_questions":"Which workflows?","counter_observations":"Some teams use one tool.","evidence_limits":"Limited coverage."}'::jsonb$$;
create function pg_temp.handoff(req uuid default '78c00000-0000-4000-8000-000000000010') returns uuid language sql as $$select public.handoff_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),req,'Private exploration','My own starting description',array[pg_temp.id('s1')],array[pg_temp.id('s1')],true)$$;
-- Purpose-bound synthetic fixtures. Reviews below use production APIs.
insert into public.radar_sources(id,name,domain,allowed_path,source_type,retrieval_method,is_public,permission_state,status,source_language,region,target_context,source_nature,source_origin,review_due_at,revision)
values('78c00000-0000-4000-8000-000000000101','Fixture source A','fixture.invalid','/','public_web','manual_url',true,'approved','active','en','unknown','IT small teams','direct','primary',now()+interval '90 days',2),
('78c00000-0000-4000-8000-000000000102','Fixture source B','fixture.invalid','/','public_forum','manual_url',true,'approved','active','de','EU','IT small teams','direct','unknown',now()+interval '90 days',2);
insert into public.radar_signals(id,source_id,source_url,source_date,source_language,summary_language,summary,problem_observation,affected_context,tags,review_status,review_due_at,delete_after,revision,approved_source_revision,url_fingerprint)
select ('78c00000-0000-4000-8000-'||lpad((200+n)::text,12,'0'))::uuid,case when n=1 then '78c00000-0000-4000-8000-000000000101'::uuid else '78c00000-0000-4000-8000-000000000102'::uuid end,'https://fixture.invalid/'||n,case when n=1 then '2026-09-01'::date when n=2 then '2026-10-01'::date end,case when n=1 then 'en' else 'de' end,'en','Summary fixture '||n,'Observation fixture '||n,'Small teams',array['workflow'],'relevant',now()+interval '180 days',null,3,2,'fixture-'||n from generate_series(1,3)n;
insert into ids values('s1','78c00000-0000-4000-8000-000000000201'),('s2','78c00000-0000-4000-8000-000000000202'),('s3','78c00000-0000-4000-8000-000000000203');
set local role authenticated;
select set_config('request.jwt.claim.sub','78c00000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.list_radar_hypotheses()$$,'42501','platform_admin_required','Normal user cannot list hypotheses');
select throws_ok($$select public.save_radar_hypothesis(null,null,pg_temp.input())$$,'42501','platform_admin_required','Normal user cannot create');
select throws_ok($$select public.list_radar_imports()$$,'42501','platform_admin_required','Normal user cannot inspect provenance');
select throws_ok($$select public.redact_radar_imports(pg_temp.id('s1'),true)$$,'42501','platform_admin_required','Normal user cannot redact');
select set_config('request.jwt.claim.sub','78c00000-0000-4000-8000-000000000001',true);
select throws_ok($$select * from public.radar_hypotheses$$,'42501',null,'Admin has no direct table reads');
select throws_ok($$select public.radar_hypothesis_changed(gen_random_uuid(),'edited')$$,'42501',null,'Internal helper is not callable');
select throws_ok($$select public.save_radar_hypothesis(null,null,pg_temp.input()||'{"created_by":"78c00000-0000-4000-8000-000000000002"}')$$,'23514','radar_field_invalid','Cannot forge actor');
select throws_ok($$select public.save_radar_hypothesis(null,null,pg_temp.input()||jsonb_build_object('title',repeat('x',161)))$$,'23514',null,'DB enforces text limits');
insert into ids values('h',public.save_radar_hypothesis(null,null,pg_temp.input()));
select is(public.get_radar_hypothesis(pg_temp.id('h'))->>'status','draft','Starts draft');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->>'created_by','78c00000-0000-4000-8000-000000000001','Actor is session user');
select throws_ok($$select pg_temp.handoff()$$,'23514','radar_review_required','Draft cannot hand off');
select throws_ok($$select public.review_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),'reviewed')$$,'23514','radar_evidence_unavailable','Empty hypothesis cannot be approved');
select throws_ok($$select public.link_radar_hypothesis_signal(pg_temp.id('h'),pg_temp.hrev(),pg_temp.id('s1'),2)$$,'23514','radar_signal_unavailable','Exact signal revision required');
select throws_ok($$select public.link_radar_hypothesis_signal(pg_temp.id('h'),pg_temp.hrev(),gen_random_uuid(),3)$$,'23514','radar_signal_unavailable','Manipulated signal rejected');
select public.link_radar_hypothesis_signal(pg_temp.id('h'),pg_temp.hrev(),pg_temp.id('s1'),3,'original-1');
select lives_ok($$select public.review_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),'reviewed')$$,'One signal is enough for explicit human review');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'signals','1','One usable indication transparent');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->>'status','reviewed','Reviewed state');
select is((public.get_radar_hypothesis(pg_temp.id('h'))->>'review_due_at')::timestamptz,now()+interval '180 days','Review expires after 180 days');
select public.link_radar_hypothesis_signal(pg_temp.id('h'),pg_temp.hrev(),pg_temp.id('s2'),3,'original-1');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->>'status','draft','Changing membership invalidates review');
select public.link_radar_hypothesis_signal(pg_temp.id('h'),pg_temp.hrev(),pg_temp.id('s3'),3);
select public.link_radar_hypothesis_signal(pg_temp.id('h'),pg_temp.hrev(),pg_temp.id('s1'),3,'original-1');
select is(jsonb_array_length(public.get_radar_hypothesis(pg_temp.id('h'))->'signals'),3,'Duplicate association counts once');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'signals','3','Three usable signals');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'sources','2','Register sources distinct');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'domains','1','Shared domain is one domain');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'origins','1','Crossposts share one manual origin');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'unknown_origins','1','Unknown origin not inferred independent');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'earliest_date','2026-09-01','Earliest source date');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'latest_date','2026-10-01','Latest observation date');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'unknown_dates','1','Missing date transparent');
select is(jsonb_array_length(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->'languages'),2,'Languages shown');
select ok(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->'regions' ? 'unknown','Unknown region retained');
select ok(not (public.get_radar_hypothesis(pg_temp.id('h'))->'evidence' ? 'score'),'No score');
insert into ids values('h2',public.save_radar_hypothesis(null,null,pg_temp.input()));
select lives_ok($$select public.link_radar_hypothesis_signal(pg_temp.id('h2'),1,pg_temp.id('s1'),3)$$,'One signal can support two hypotheses');
select public.review_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),'reviewed');
select public.save_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),pg_temp.input()||'{"counter_observations":"Updated counter-observation"}');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->>'status','draft','Counter-observation edit invalidates review');
select public.review_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),'reviewed');
reset role;
update public.radar_signals set review_due_at=now()-interval '1 second' where id=pg_temp.id('s3');
set local role authenticated;
select is(public.get_radar_hypothesis(pg_temp.id('h'))->>'status','draft','Expiry dynamically invalidates hypothesis');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'signals','2','Expired signal not counted');
select ok(not exists(select 1 from jsonb_array_elements(public.get_radar_hypothesis(pg_temp.id('h'))->'signals')x where x->>'id'=pg_temp.id('s3')::text and x ? 'summary'),'Expired signal text masked');
select throws_ok($$select pg_temp.handoff()$$,'23514','radar_review_required','Expired evidence blocks handoff');
reset role;
update public.radar_signals set review_due_at=now()+interval '180 days',revision=4 where id=pg_temp.id('s3');
set local role authenticated;
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'signals','2','New revision never silently replaces old');
select public.link_radar_hypothesis_signal(pg_temp.id('h'),pg_temp.hrev(),pg_temp.id('s3'),4);
select public.review_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),'reviewed');
select set_config('request.jwt.claim.sub','78c00000-0000-4000-8000-000000000003',true);
select throws_ok($$select pg_temp.handoff()$$,'42501','workspace_forbidden','Admin without CONNECT cannot hand off');
select set_config('request.jwt.claim.sub','78c00000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.handoff_radar_hypothesis(pg_temp.id('h'),1,gen_random_uuid(),'Title','',array[pg_temp.id('s1')],'{}',true)$$,'40001','radar_conflict','Stale hypothesis revision rejected');
select throws_ok($$select public.handoff_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),gen_random_uuid(),'Title','',array[gen_random_uuid()],'{}',true)$$,'23514','radar_signal_unavailable','Foreign signal ID rejected');
select throws_ok($$select public.handoff_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),gen_random_uuid(),'Title','','{}',array[pg_temp.id('s1')],true)$$,'23514','radar_invalid','No link without deliberately selected signal');
select throws_ok($$select public.handoff_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),gen_random_uuid(),'Title','','{}','{}',false)$$,'23514','radar_invalid','Explicit confirmation required');
reset role;
update public.network_profiles set status='paused' where user_id='78c00000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select pg_temp.handoff()$$,'42501','workspace_forbidden','Admin with inactive profile cannot hand off');
reset role;
update public.network_profiles set status='active' where user_id='78c00000-0000-4000-8000-000000000001';
create function pg_temp.fail_import() returns trigger language plpgsql as $$begin if new.type='assumption' then raise exception 'synthetic_import_failure'; end if; return new; end$$;
create trigger synthetic_import_failure before insert on public.network_problem_workspace_entries for each row execute function pg_temp.fail_import();
set local role authenticated;
select throws_ok($$select pg_temp.handoff()$$,'P0001','synthetic_import_failure','Injected failure after workspace creation rolls whole handoff back');
reset role;
select is((select count(*)::int from public.network_problem_workspaces where owner_user_id='78c00000-0000-4000-8000-000000000001'),0,'No partial workspace survives failed entry creation');
select is((select count(*)::int from public.radar_workspace_handoffs where actor='78c00000-0000-4000-8000-000000000001'),0,'No partial provenance survives failed entry creation');
drop trigger synthetic_import_failure on public.network_problem_workspace_entries;
set local role authenticated;
insert into ids values('w',pg_temp.handoff());
select is(pg_temp.handoff(),pg_temp.id('w'),'Retry is idempotent');
select throws_ok($$select public.handoff_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),'78c00000-0000-4000-8000-000000000010','Changed payload','','{}','{}',true)$$,'40001','radar_conflict','Same request cannot change payload');
select is(public.get_problem_workspace(pg_temp.id('w'))->>'role','owner','Session actor owns workspace');
select is(jsonb_array_length(public.get_problem_workspace(pg_temp.id('w'))->'members'),1,'No external people or reviewers become members');
select is(jsonb_array_length(public.get_problem_workspace(pg_temp.id('w'))->'entries'),2,'Only assumption and selected signal copied');
select ok(public.get_problem_workspace(pg_temp.id('w'))::text not like '%Summary fixture 2%','Unselected summary not copied');
select is(public.get_problem_workspace_publication_preview(pg_temp.id('w'))->'problem','null'::jsonb,'No network_problem created');
select is(jsonb_array_length(public.get_problem_workspace_development(pg_temp.id('w'))->'opportunities'),0,'No opportunity/venture created');
insert into ids select 'import', (x->>'id')::uuid from jsonb_array_elements(public.get_problem_workspace(pg_temp.id('w'))->'entries')x where x->>'type'='perspective';
insert into ids values('own',public.save_problem_workspace_entry(pg_temp.id('w'),'observation','PRIVATE_UNRELATED'));
select public.save_problem_workspace_entry(pg_temp.id('w'),'perspective','PRIVATE_REWRITTEN','https://fixture.invalid/1','External source',pg_temp.id('import'));
select set_config('request.jwt.claim.sub','78c00000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.get_problem_workspace(pg_temp.id('w'))$$,'42501','workspace_forbidden','Other radar admin cannot read workspace');
select ok(public.list_radar_imports()::text not like '%PRIVATE_%','Provenance never leaks private text');
select ok(public.list_radar_imports()::text not like '%'||pg_temp.id('w')::text||'%','No workspace IDs in admin counts');
select public.review_radar_source('78c00000-0000-4000-8000-000000000101',2,'denied','withdrawn',null);
select is(public.get_radar_hypothesis(pg_temp.id('h'))->>'status','draft','Source withdrawn invalidates review immediately');
select set_config('request.jwt.claim.sub','78c00000-0000-4000-8000-000000000001',true);
select throws_ok($$select pg_temp.handoff('78c00000-0000-4000-8000-000000000011')$$,'23514','radar_review_required','New handoffs blocked immediately');
select ok(public.get_problem_workspace(pg_temp.id('w'))::text like '%PRIVATE_REWRITTEN%','Owner-written text survives dynamic restriction');
select ok(public.get_problem_workspace(pg_temp.id('w'))::text not like '%https://fixture.invalid/1%','Untouched link hidden immediately');
select ok(public.get_problem_workspace(pg_temp.id('w'))::text not like '%Small software teams may repeat%','Dependent untouched assumption hidden immediately');
select set_config('request.jwt.claim.sub','78c00000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.redact_radar_imports(pg_temp.id('s1'),false)$$,'23514','radar_confirmation_required','Redaction needs confirmation');
select throws_ok($$select public.redact_radar_imports(pg_temp.id('own'),true)$$,'23514','radar_invalid','Entry ID cannot target arbitrary private text');
select is(public.redact_radar_imports(pg_temp.id('s1'),true),2,'Only controlled assumption and source link redacted');
select is(public.redact_radar_imports(pg_temp.id('s1'),true),0,'Redaction retry harmless');
select set_config('request.jwt.claim.sub','78c00000-0000-4000-8000-000000000001',true);
select ok(public.get_problem_workspace(pg_temp.id('w'))::text like '%PRIVATE_REWRITTEN%','Redaction preserves independently rewritten text');
select ok(public.get_problem_workspace(pg_temp.id('w'))::text like '%PRIVATE_UNRELATED%','Unrelated private entry untouched');
select ok(public.get_problem_workspace(pg_temp.id('w'))::text not like '%https://fixture.invalid/1%','Controlled link permanently removed');
reset role;
select is((select content from public.network_problem_workspace_entries where id=pg_temp.id('import')),'PRIVATE_REWRITTEN','No hidden destructive owner text change');
select ok((select source_url is null from public.network_problem_workspace_entries where id=pg_temp.id('import')),'Raw controlled URL redacted');
select ok(not exists(select 1 from public.radar_hypothesis_events where hypothesis_id=pg_temp.id('h') and actor is null),'Actor on all hypothesis events');
update public.radar_signals set usage_block=true where id=pg_temp.id('s2');
set local role authenticated;
select is(public.get_radar_hypothesis(pg_temp.id('h'))->'evidence'->>'signals','1','Blocked signal absent from evidence');
select public.review_radar_hypothesis(pg_temp.id('h'),pg_temp.hrev(),'archived');
select is(public.get_radar_hypothesis(pg_temp.id('h'))->>'status','archived','Archive terminal');
select throws_ok($$select pg_temp.handoff(gen_random_uuid())$$,'23514','radar_review_required','Archived cannot hand off');
reset role;
update public.radar_hypotheses set delete_after=now()-interval '1 day' where id=pg_temp.id('h');
set local role authenticated;
select is(public.get_radar_hypothesis(pg_temp.id('h')),null::jsonb,'Expired hypothesis hidden before cleanup');
select public.purge_radar_hypotheses();
select lives_ok($$select public.get_problem_workspace(pg_temp.id('w'))$$,'Hypothesis retention does not delete workspace');
reset role;
delete from public.radar_signals where id=pg_temp.id('s1');
select ok(exists(select 1 from public.radar_workspace_handoff_items where signal_key=pg_temp.id('s1') and signal_id is null),'Minimal provenance survives signal purge');
delete from public.platform_admins where user_id='78c00000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select public.get_radar_hypothesis(pg_temp.id('h2'))$$,'42501','platform_admin_required','Admin withdrawal effective next read');
reset role;
set local role anon;
select throws_ok($$select public.list_radar_hypotheses()$$,'42501',null,'Anonymous has no RPC access');
select throws_ok($$select * from public.radar_workspace_handoff_items$$,'42501',null,'Anonymous has no provenance access');
reset role;
select ok(not has_table_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,DELETE'),'No direct client grants: '||c.relname) from pg_class c where c.relnamespace='public'::regnamespace and c.relname in('radar_hypotheses','radar_hypothesis_signals','radar_hypothesis_events','radar_workspace_handoffs','radar_workspace_handoff_items');
select ok(c.relrowsecurity,'RLS: '||c.relname) from pg_class c where c.relnamespace='public'::regnamespace and c.relname in('radar_hypotheses','radar_hypothesis_signals','radar_hypothesis_events','radar_workspace_handoffs','radar_workspace_handoff_items');
select * from finish();
rollback;
