import Link from "next/link"; import { getTranslations } from "next-intl/server";
import { requireNetworkMember } from "@/features/network/networkAccess";
import { NetworkListingForm } from "@/features/network/NetworkListingForm";
import { NETWORK_CATEGORIES, NETWORK_DIRECTIONS, coFounderBridgeHref, isOneOf } from "@/features/network/networkTypes";
import { getProfileBasicsRow } from "@/features/profile/profileData"; import { hasProfileRole } from "@/features/profile/profileRoles";
export default async function NewListingPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const t = await getTranslations("network"); const params = await searchParams; const { client, user } = await requireNetworkMember("/network/listings/new");
  const direction = isOneOf(NETWORK_DIRECTIONS, params.direction) ? params.direction : undefined;
  if (params.category === "cofounder") { const baseProfile = await getProfileBasicsRow(client, user.id).catch(() => null); const href = coFounderBridgeHref(hasProfileRole(baseProfile?.roles, "founder")); return <main className="mx-auto max-w-2xl px-5 py-10"><Link href="/network" className="inline-flex min-h-11 items-center text-sm font-semibold text-slate-600">← {t("navigation.network")}</Link><section className="mt-3 rounded-3xl border border-violet-200 bg-violet-50 p-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-700">{t("cofounder.eyebrow")}</p><h1 className="mt-3 text-3xl font-semibold">{t("cofounder.title")}</h1><p className="mt-3 leading-7 text-slate-700">{t("cofounder.text")}</p><Link href={href} className="mt-6 inline-flex min-h-11 items-center rounded-full bg-slate-950 px-5 text-sm font-semibold text-white">{t(hasProfileRole(baseProfile?.roles, "founder") ? "cofounder.cta" : "cofounder.setupFounder")}</Link></section></main>; }
  const category = isOneOf(NETWORK_CATEGORIES, params.category) ? params.category : undefined;
  if (!category) return <main className="mx-auto max-w-4xl px-5 py-10"><Link href="/network" className="inline-flex min-h-11 items-center text-sm font-semibold text-slate-600">← {t("navigation.network")}</Link><h1 className="mt-3 text-3xl font-semibold">{t("create.kindTitle")}</h1><p className="mt-2 text-slate-600">{t("create.kindText")}</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{[...NETWORK_CATEGORIES,"cofounder"].map((value) => <Link key={value} href={`/network/listings/new?direction=${direction || "seeking"}&category=${value}`} className="min-h-20 rounded-2xl border border-slate-200 bg-white p-5 font-semibold hover:border-slate-400">{value === "cofounder" ? t("categories.cofounder") : t(`categories.${value}`)}</Link>)}</div></main>;
  return <main className="mx-auto max-w-4xl px-5 py-10"><Link href="/network" className="inline-flex min-h-11 items-center text-sm font-semibold text-slate-600">← {t("navigation.network")}</Link><h1 className="mt-3 text-3xl font-semibold">{t("create.editorTitle")}</h1>{params.error ? <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">{t(`errors.${params.error}`)}</p> : null}<div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6"><NetworkListingForm direction={direction} category={category} t={t} /></div></main>;
}
