import type { Metadata } from "next";
import Link from "next/link";
import { requirePlatformAdmin } from "@/features/moderation/access";
import { workstyleStatistics } from "@/features/instruments/workstyle/analytics";
import type { ResearchRow } from "@/features/instruments/workstyle/data";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Workstyle Research-Pretest – Administration", robots: { index: false, follow: false }, referrer: "no-referrer" };
const number = (value: number | null, suffix = "") => value === null ? "–" : `${Math.round(value * 10) / 10}${suffix}`;

export default async function WorkstyleResearchAdminPage() {
  const client = await requirePlatformAdmin();
  const { data, error } = await client.rpc("get_workstyle_research_dataset");
  if (error) return <main className="mx-auto max-w-4xl px-4 py-10"><p role="alert">Die Research-Auswertung konnte nicht geladen werden.</p></main>;
  const stats = workstyleStatistics(data as ResearchRow[]);
  return <main lang="de" className="mx-auto max-w-6xl space-y-8 px-4 py-10 text-slate-900">
    <div><Link href="/account" className="underline">Account</Link><h1 className="mt-4 text-3xl font-semibold">Workstyle Research-Pretest</h1><p className="mt-3">8.5a-v1 · 20 identische Core-Items + Form A/B/C. Nur nicht widerrufene Researchteilnahmen. Deskriptive Auswertung ohne automatische Itembewertung.</p></div>
    <dl className="grid gap-5 sm:grid-cols-3"><div><dt>Gesamt-N</dt><dd className="text-2xl">{stats.n}</dd></div><div><dt>N je Form</dt><dd>{stats.forms.map(f => `${f.form}: ${f.n}`).join(" · ")}</dd></div><div><dt>Completion Rate</dt><dd>{number(stats.completionRate === null ? null : stats.completionRate * 100, "%")} ({stats.completed})</dd></div><div><dt>Median Bearbeitungsdauer</dt><dd>{number(stats.medianDurationMs === null ? null : stats.medianDurationMs / 60000, " Min.")}</dd></div></dl>
    <p className="text-sm text-slate-600">Dauer = Zeit zwischen Start und Abschluss einschließlich Unterbrechungen. Antwortzeiten sind beobachtete Zeit bis zum Speichern, keine Messung aktiver Aufmerksamkeit. Missing-% bezieht sich auf gespeicherte Antworten; nicht beantwortete Items bleiben getrennt.</p>
    <a href="/admin/research/workstyle-pretest/export" className="inline-flex min-h-11 items-center rounded-xl bg-violet-800 px-5 text-white">Long-Format als CSV exportieren</a>
    <section><h2 className="mb-3 text-xl font-semibold">Offene Sessions: erste noch nicht beantwortete Position</h2><p className="text-sm">Noch laufende Teilnahmen sind enthalten; diese Ansicht beweist keinen endgültigen Abbruch.</p>{stats.dropPositions.length ? <ul>{stats.dropPositions.map(row => <li key={row.position}>{row.position}: {row.n}</li>)}</ul> : <p>Keine offenen Sessions.</p>}</section>
    <section><h2 className="mb-3 text-xl font-semibold">Items</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Antworten, Missing und Feedback je Item</caption><thead><tr>{["Item / Nutzung", "N / zugewiesen", "Missing", "Missing %", "Verteilung 1 / 2 / 3 / 4 / 5", "Median Antwortzeit", "Flags: unklar / unpassend / erwünscht"].map(h => <th key={h} scope="col" className="border-b p-3">{h}</th>)}</tr></thead><tbody>{stats.items.map(row => <tr key={row.item.item_key}><th scope="row" className="border-b p-3">{row.item.item_key}<span className="block font-normal">{row.item.usage === "core" ? "Core" : `Research ${row.item.form}`}</span></th><td className="border-b p-3">{row.n} / {row.eligible}</td><td className="border-b p-3">{row.missing}</td><td className="border-b p-3">{number(row.missingPercent, "%")}</td><td className="border-b p-3">{row.distribution.join(" / ")}</td><td className="border-b p-3">{number(row.medianTimeMs === null ? null : row.medianTimeMs / 1000, " s")}</td><td className="border-b p-3">{row.flags.unclear} / {row.flags.unsuitable} / {row.flags.desirable}</td></tr>)}</tbody></table></div></section>
    <section><h2 className="mb-3 text-xl font-semibold">Core-Vergleich zwischen den Formen</h2><p className="mb-3 text-sm">Je Form: N, Missing und Verteilung der fünf Antwortkategorien. Keine Skalenmittelwerte und keine automatischen Qualitätsurteile.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th scope="col" className="p-3">Core-Item</th>{["A", "B", "C"].map(form => <th key={form} scope="col" className="p-3">Form {form}</th>)}</tr></thead><tbody>{stats.coreByForm.map(row => <tr key={row.itemKey}><th scope="row" className="border-b p-3">{row.itemKey}</th>{row.forms.map(form => <td key={form.form} className="border-b p-3">N={form.n}; Missing={form.missing}; {form.distribution.join(" / ")}</td>)}</tr>)}</tbody></table></div></section>
    <section><h2 className="mb-3 text-xl font-semibold">Freiwilliges Feedback</h2><p className="text-sm">Freitext kann selbst identifizierende Angaben enthalten. Er ist nicht im Antwortexport enthalten.</p>{stats.feedback.map(row => <details key={row.session_id} className="mt-4 rounded-xl border p-4"><summary>Form {row.form} · Session {row.session_id.slice(0, 8)} · Verständlichkeit {row.feedback.clarity ?? "–"}</summary><dl className="mt-3 space-y-3">{Object.entries(row.feedback).map(([key, value]) => <div key={key}><dt className="font-medium">{key}</dt><dd className="whitespace-pre-wrap break-words">{Array.isArray(value) ? value.join(", ") : String(value)}</dd></div>)}</dl></details>)}</section>
  </main>;
}
