import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getLocale, getTranslations } from "next-intl/server";
import { markFounderInTheWildConversationAction, openFounderInTheWildRevealAction, unmarkFounderInTheWildConversationAction } from "@/features/founderInTheWild/founderInTheWildActions";
import { getFounderInTheWildRound, getFounderInTheWildTeam, getOpenedFounderInTheWildReveal } from "@/features/founderInTheWild/founderInTheWildData";
import { normalizeLocale } from "@/i18n/config";
import { createClient } from "@/lib/supabase/server";

export default async function FounderInTheWildPromptReveal({ params }: { params: Promise<{ teamId: string; roundId: string; position: string }> }) {
  const { teamId, roundId, position: raw } = await params; const position = Number(raw); if (!Number.isInteger(position) || position < 0 || position > 4) notFound();
  const base = `/teams/${encodeURIComponent(teamId)}/collaboration-lab/founder-in-the-wild/${encodeURIComponent(roundId)}`; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect(`/login?next=${encodeURIComponent(`${base}/reveal/${position}`)}`);
  const team = await getFounderInTheWildTeam(teamId, user.id, supabase); if (!team) notFound(); const round = await getFounderInTheWildRound(team, roundId, user.id, supabase); const prompt = round?.prompts.find((entry) => entry.position === position); if (!round || !prompt) notFound(); if (!round.wholeRoundAnswerComplete) redirect(base);
  const [t, rawLocale] = await Promise.all([getTranslations("founderInTheWild.reveal"), getLocale()]); const locale = normalizeLocale(rawLocale); const partnerName = round.partner.displayName ?? (locale === "de" ? "dein Co-Founder" : "your co-founder"); const opened = round.openedPromptPositions.includes(position); const data = opened ? await getOpenedFounderInTheWildReveal({ team, roundId, position, userId: user.id, client: supabase }) : null;
  if (!opened) return <main className="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6 sm:py-10"><Link href={`${base}/reveal`} className="text-sm text-slate-600 underline">{t("overview")}</Link><section className="mt-6 rounded-[30px] border border-violet-200 bg-gradient-to-br from-violet-50 to-amber-50 p-8 text-center"><h1 className="text-3xl font-semibold">{prompt.content.title[locale]}</h1><p className="mt-3 text-sm text-slate-600">{t("sealed")}</p><form action={openFounderInTheWildRevealAction.bind(null, teamId, roundId, position)} className="mt-6"><button className="min-h-12 rounded-xl bg-violet-700 px-6 py-3 text-sm font-semibold text-white">{t("open")}</button></form></section></main>;
  if (!data) notFound(); const reveal = data.reveal; const label = (keys: string[], type: "moves" | "matters" | "needs") => keys.flatMap((key) => reveal.prompt.content[type].find((choice) => choice.key === key)?.label[locale] ?? []); const ownMarked = round.conversationMarkers.find((entry) => entry.roundPromptId === prompt.roundPromptId)?.participantUserIds.includes(user.id) ?? false; const partnerMarked = round.conversationMarkers.find((entry) => entry.roundPromptId === prompt.roundPromptId)?.participantUserIds.includes(round.partner.userId) ?? false; const status = ownMarked && partnerMarked ? t("markedBoth") : partnerMarked ? t("markedPartner", { name: partnerName }) : ownMarked ? t("markedOwn") : null; const next = round.prompts.find((entry) => entry.position > position)?.position;
  const panel = (title: string, keys: string[], type: "moves" | "matters" | "needs") => <article className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-semibold text-slate-700">{title}</h3><ul className="mt-3 grid gap-2">{label(keys, type).map((value) => <li key={value} className="text-sm leading-6 text-slate-900">{value}</li>)}</ul></article>;
  return <main className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 sm:py-10"><Link href={`${base}/reveal`} className="text-sm font-medium text-slate-600 underline-offset-4 hover:underline">{t("overview")}</Link><header className="mt-6 rounded-[30px] border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-amber-50 p-6 sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-700">{t("eyebrow")}</p><h1 className="mt-3 text-3xl font-semibold">{prompt.content.title[locale]}</h1><p className="mt-4 text-base leading-7 text-slate-700">{prompt.content.situation[locale]}</p></header><p className="mt-6 inline-flex rounded-full bg-violet-100 px-3 py-1.5 text-xs font-semibold text-violet-900">{t(reveal.own.move[0] === reveal.partner.move[0] ? "same" : "different")}</p>
    <section className="mt-4 grid gap-4 md:grid-cols-2">{panel(t("yourMove"), reveal.own.move, "moves")}{panel(t("partnerMove", { name: partnerName }), reveal.partner.move, "moves")}{panel(t("yourMatters"), reveal.own.matters, "matters")}{panel(t("partnerMatters", { name: partnerName }), reveal.partner.matters, "matters")}{panel(t("yourNeed"), reveal.own.need, "needs")}{panel(t("partnerNeed", { name: partnerName }), reveal.partner.need, "needs")}</section>
    <section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50/50 p-5"><h2 className="text-lg font-semibold">{t("talkTitle")}</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-6 text-slate-700"><li>{t("talk1")}</li><li>{t("talk2")}</li><li>{t("talk3")}</li></ol></section>
    <section id="conversation-marker" className="mt-6 rounded-2xl border border-violet-200 bg-violet-50/50 p-5"><h2 className="text-lg font-semibold">{t("markerTitle")}</h2>{status ? <p className="mt-2 text-sm font-medium text-violet-900">{status}</p> : null}<p className="mt-2 text-sm text-slate-600">{t("visible")}</p><form action={(ownMarked ? unmarkFounderInTheWildConversationAction : markFounderInTheWildConversationAction).bind(null, teamId, roundId, position, prompt.roundPromptId)} className="mt-4"><button aria-pressed={ownMarked} className="min-h-11 rounded-xl border border-violet-300 bg-white px-4 py-2 text-sm font-semibold text-violet-900 focus-visible:ring-2 focus-visible:ring-violet-500">{t(ownMarked ? "unmark" : "mark")}</button></form></section>
    <nav className="mt-6 flex justify-end">{next === undefined ? <Link href={`${base}/reveal`} className="inline-flex min-h-11 items-center rounded-xl bg-violet-700 px-5 py-3 text-sm font-semibold text-white">{t("roundOverview")}</Link> : <Link href={`${base}/reveal/${next}`} className="inline-flex min-h-11 items-center rounded-xl bg-violet-700 px-5 py-3 text-sm font-semibold text-white">{t("next")}</Link>}</nav>
  </main>;
}
