import type { EventAnswerValue, EventQuestion } from "@/features/events/eventTypes";

export const EVENT_ANSWER_SCALE: readonly EventAnswerValue[] = [0, 25, 50, 75, 100] as const;

export const EVENT_CORE_QUESTIONS: readonly EventQuestion[] = [
  {
    key: "core_vision_ambition",
    kind: "core",
    dimensionId: "company_logic",
    prompt: "Wenn du gruendest: Wie gross willst du wirklich bauen?",
    leftLabel: "fokussiert und kontrolliert wachsen",
    rightLabel: "so gross wie moeglich",
    compareWeight: 1.1,
  },
  {
    key: "core_vision_time_horizon",
    kind: "core",
    dimensionId: "commitment",
    prompt: "Wie stark soll Gruenden gerade dein Leben bestimmen?",
    leftLabel: "wichtig, aber mit klaren Grenzen",
    rightLabel: "die naechsten Jahre klar im Zentrum",
    compareWeight: 1,
  },
  {
    key: "core_decision_speed",
    kind: "core",
    dimensionId: "decision_logic",
    prompt: "Wenn etwas wichtig wird: lieber schnell callen oder erst sauber durchdenken?",
    leftLabel: "erst ordentlich durchgehen",
    rightLabel: "lieber frueh entscheiden",
    compareWeight: 1.1,
  },
  {
    key: "core_execution_tempo",
    kind: "core",
    dimensionId: "commitment",
    prompt: "Wie intensiv soll sich Gruenden gerade im Alltag anfuehlen?",
    leftLabel: "stark, aber mit Luft",
    rightLabel: "hoch, schnell, kompromisslos",
    compareWeight: 1.2,
  },
  {
    key: "core_risk_orientation",
    kind: "core",
    dimensionId: "risk_orientation",
    prompt: "Wie gut fuehlen sich mutige Wetten unter Unsicherheit fuer dich an?",
    leftLabel: "lieber erst absichern",
    rightLabel: "lieber mutig nach vorn",
    compareWeight: 1.1,
  },
  {
    key: "core_role_clarity",
    kind: "core",
    dimensionId: "work_structure",
    prompt: "Wie frueh wollt ihr sauber sagen: Das ist dein Bereich, das ist meiner?",
    leftLabel: "erst gemeinsam reinfinden",
    rightLabel: "frueh klar aufteilen",
    compareWeight: 1.15,
  },
  {
    key: "core_visibility_sync",
    kind: "core",
    dimensionId: "work_structure",
    prompt: "Wie eng willst du mit einem Co-Founder im Alltag wirklich verbunden sein?",
    leftLabel: "viel Freiraum dazwischen",
    rightLabel: "eng im Loop bleiben",
    compareWeight: 1.15,
  },
  {
    key: "core_conflict_addressing",
    kind: "core",
    dimensionId: "conflict_style",
    prompt: "Wenn etwas schief haengt: Wie direkt willst du es ansprechen?",
    leftLabel: "erst vorsichtig antasten",
    rightLabel: "lieber sofort auf den Tisch",
    compareWeight: 1.2,
  },
] as const;

export const EVENT_FORCED_QUESTIONS: readonly EventQuestion[] = [
  {
    key: "forced_exit_horizon",
    kind: "forced",
    tensionKey: "exit_horizon",
    prompt: "Was reizt dich an einer Gruendung mehr?",
    leftLabel: "etwas auf Jahre bauen",
    rightLabel: "frueh auf Hebel und Exit gehen",
    helperText: "Wenn ihr hier weit auseinanderliegt, wird es oft schnell interessant.",
    tensionWeight: 1.3,
  },
  {
    key: "forced_sync_vs_autonomy",
    kind: "forced",
    tensionKey: "sync_vs_autonomy",
    prompt: "Was fuehlt sich in einem fruehen Team besser an?",
    leftLabel: "taeglich eng draufschauen",
    rightLabel: "viel Freiraum im Alltag",
    helperText: "Das taucht im Alltag meist frueher auf als gedacht.",
    tensionWeight: 1.2,
  },
  {
    key: "forced_speed_vs_assurance",
    kind: "forced",
    tensionKey: "speed_vs_assurance",
    prompt: "Wenn es drauf ankommt: Was sollte eher gewinnen?",
    leftLabel: "schnell in Bewegung kommen",
    rightLabel: "lieber einmal sauber pruefen",
    helperText: "Hier merkt man spaeter oft, wie ihr unter Druck tickt.",
    tensionWeight: 1.25,
  },
  {
    key: "forced_risk_vs_stability",
    kind: "forced",
    tensionKey: "risk_vs_stability",
    prompt: "Was fuehlt sich fuer ein fruehes Gruendungsteam attraktiver an?",
    leftLabel: "hart auf Chancen gehen",
    rightLabel: "erst Stabilitaet halten",
    helperText: "Das ist selten Theorie - eher Nervensystem im echten Betrieb.",
    tensionWeight: 1.3,
  },
  {
    key: "forced_roles_vs_shared",
    kind: "forced",
    tensionKey: "roles_vs_shared",
    prompt: "Wie sollte Verantwortung am Anfang eher aussehen?",
    leftLabel: "klar aufgeteilt",
    rightLabel: "viel gemeinsam tragen",
    helperText: "Daran merkt man schnell, wie ihr Ownership wirklich lebt.",
    tensionWeight: 1.15,
  },
] as const;

export const EVENT_QUESTIONS: readonly EventQuestion[] = [
  ...EVENT_CORE_QUESTIONS,
  ...EVENT_FORCED_QUESTIONS,
] as const;
