import type { EventAnswerValue, EventQuestion } from "@/features/events/eventTypes";

export const EVENT_ANSWER_SCALE: readonly EventAnswerValue[] = [0, 25, 50, 75, 100] as const;

export const EVENT_CORE_QUESTIONS: readonly EventQuestion[] = [
  {
    key: "core_vision_ambition",
    kind: "core",
    dimensionId: "company_logic",
    prompt: "Wie gross sollte die unternehmerische Ambition in den naechsten Jahren sein?",
    leftLabel: "fokussiert und realistisch wachsen",
    rightLabel: "moeglichst gross und schnell bauen",
    helperText: "Es geht um euren Grundzug zwischen nachhaltigem Aufbau und maximalem Hebel.",
    compareWeight: 1.1,
  },
  {
    key: "core_vision_time_horizon",
    kind: "core",
    dimensionId: "company_logic",
    prompt: "Wie weit denkst du bei zentralen Unternehmensentscheidungen voraus?",
    leftLabel: "naechste klare Schritte zuerst",
    rightLabel: "langfristige Richtung frueh mitdenken",
    helperText: "Diese Achse zeigt, wie stark jemand auf unmittelbare Traktion oder auf den groesseren Bogen schaut.",
    compareWeight: 1,
  },
  {
    key: "core_decision_speed",
    kind: "core",
    dimensionId: "decision_logic",
    prompt: "Wie schnell sollten wichtige Entscheidungen in einem fruehen Team fallen?",
    leftLabel: "erst gruendlich klaeren",
    rightLabel: "lieber frueh entscheiden",
    helperText: "Unterschiede hier sind oft kein Ausschluss, aber klarer Gespraechsbedarf.",
    compareWeight: 1.1,
  },
  {
    key: "core_execution_tempo",
    kind: "core",
    dimensionId: "commitment",
    prompt: "Wie intensiv sollte das gemeinsame Umsetzungstempo im Alltag sein?",
    leftLabel: "eher planbar und nachhaltig",
    rightLabel: "hoch und kompromisslos",
    helperText: "Die Frage zielt auf Einsatzrealitaet, nicht auf Motivation als solche.",
    compareWeight: 1.2,
  },
  {
    key: "core_risk_orientation",
    kind: "core",
    dimensionId: "risk_orientation",
    prompt: "Wie wohl fuehlst du dich mit mutigen Wetten unter Unsicherheit?",
    leftLabel: "lieber absichern",
    rightLabel: "lieber mutig nach vorn",
    helperText: "Diese Achse macht sichtbar, wie jemand Chancen und Unsicherheit zusammendenkt.",
    compareWeight: 1.1,
  },
  {
    key: "core_role_clarity",
    kind: "core",
    dimensionId: "work_structure",
    prompt: "Wie frueh sollten Rollen und Verantwortungen klar verteilt sein?",
    leftLabel: "erst gemeinsam entwickeln",
    rightLabel: "frueh klar festziehen",
    helperText: "Hilft zu verstehen, wie viel Offenheit oder Klarheit jemand zu Beginn braucht.",
    compareWeight: 1.15,
  },
  {
    key: "core_visibility_sync",
    kind: "core",
    dimensionId: "work_structure",
    prompt: "Wie eng sollte man sich im Arbeitsalltag gegenseitig auf dem Laufenden halten?",
    leftLabel: "nur an wichtigen Punkten",
    rightLabel: "sehr eng und regelmaessig",
    helperText: "Diese Frage zeigt, wie viel Mitsicht und Abstimmung sich fuer jemanden gut anfuehlt.",
    compareWeight: 1.15,
  },
  {
    key: "core_conflict_addressing",
    kind: "core",
    dimensionId: "conflict_style",
    prompt: "Wie direkt sollten Spannungen oder Zweifel im Gruendungsteam angesprochen werden?",
    leftLabel: "eher vorsichtig und dosiert",
    rightLabel: "frueh und direkt",
    helperText: "Unterschiede hier sind oft sehr gespraechsrelevant, auch wenn sonst viel passt.",
    compareWeight: 1.2,
  },
] as const;

export const EVENT_FORCED_QUESTIONS: readonly EventQuestion[] = [
  {
    key: "forced_exit_horizon",
    kind: "forced",
    tensionKey: "exit_horizon",
    prompt: "Welche Richtung fuehlt sich fuer dich in der Gruendung attraktiver an?",
    leftLabel: "langfristig aufbauen",
    rightLabel: "moeglichst schnell auf Exit spielen",
    helperText: "Hohe Unterschiede hier heissen nicht No-Fit, sondern fruehen Gespraechsbedarf.",
    tensionWeight: 1.3,
  },
  {
    key: "forced_sync_vs_autonomy",
    kind: "forced",
    tensionKey: "sync_vs_autonomy",
    prompt: "Was fuehlt sich im fruehen Teamalltag besser an?",
    leftLabel: "taeglich eng abstimmen",
    rightLabel: "mit hoher Autonomie arbeiten",
    helperText: "Diese Spannung ist oft spaeter im Alltag deutlicher als am Anfang des Kennenlernens.",
    tensionWeight: 1.2,
  },
  {
    key: "forced_speed_vs_assurance",
    kind: "forced",
    tensionKey: "speed_vs_assurance",
    prompt: "Was sollte bei wichtigen Entscheidungen eher den Ausschlag geben?",
    leftLabel: "schnell in Bewegung kommen",
    rightLabel: "stark absichern und pruefen",
    helperText: "Die Differenz zeigt vor allem, worueber man bewusst sprechen sollte.",
    tensionWeight: 1.25,
  },
  {
    key: "forced_risk_vs_stability",
    kind: "forced",
    tensionKey: "risk_vs_stability",
    prompt: "Was fuehlt sich fuer ein fruehes Gruendungsteam attraktiver an?",
    leftLabel: "aggressiv auf Chance gehen",
    rightLabel: "bewusst Stabilitaet halten",
    helperText: "Nicht als Ausschluss lesen, sondern als klares Signal fuer Grenz- und Erwartungsgespraeche.",
    tensionWeight: 1.3,
  },
  {
    key: "forced_roles_vs_shared",
    kind: "forced",
    tensionKey: "roles_vs_shared",
    prompt: "Wie sollte Verantwortung zu Beginn eher organisiert sein?",
    leftLabel: "klare Rollen frueh festziehen",
    rightLabel: "vieles gemeinsam tragen",
    helperText: "Hier geht es um Gespraechsbedarf zu Ownership, nicht um richtig oder falsch.",
    tensionWeight: 1.15,
  },
] as const;

export const EVENT_QUESTIONS: readonly EventQuestion[] = [
  ...EVENT_CORE_QUESTIONS,
  ...EVENT_FORCED_QUESTIONS,
] as const;
