import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getLocale, getTranslations } from "next-intl/server";
import { completeFounderInTheWildRoundAction, openFounderInTheWildRevealAction } from "@/features/founderInTheWild/founderInTheWildActions";
import { getFounderInTheWildRound, getFounderInTheWildTeam, getOpenedFounderInTheWildReveal } from "@/features/founderInTheWild/founderInTheWildData";
import { normalizeLocale } from "@/i18n/config";
import { createClient } from "@/lib/supabase/server";

export default async function FounderInTheWildRevealOverview({ params, searchParams }: { params: Promise<{ teamId: string; roundId: string }>; searchParams: Promise<{ result?: string }> }) {
  const [{ teamId, roundId }, query] = await Promise.all([params, searchParams]); const roundPath = `/teams/${encodeURIComponent(teamId)}/collaboration-lab/founder-in-the-wild/${encodeURIComponent(roundId)}`;
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect(`/login?next=${encodeURIComponent(`${roundPath}/reveal`)}`);
  const team = await getFounderInTheWildTeam(teamId, user.id, supabase); if (!team) notFound(); const round = await getFounderInTheWildRound(team, roundId, user.id, supabase); if (!round) notFound(); if (!round.wholeRoundAnswerComplete) redirect(roundPath);
  const [t, rawLocale] = await Promise.all([getTranslations("founderInTheWild.reveal"), getLocale()]); const locale = normalizeLocale(rawLocale); const partnerName = round.partner.displayName ?? (locale === "de" ? "dein Co-Founder" : "your co-founder");
  const allOpened = round.openedPromptPositions.length === round.prompts.length;
  const reveals = allOpened ? (await Promise.all(round.prompts.map((prompt) => getOpenedFounderInTheWildReveal({ team, roundId, position: prompt.position, userId: user.id, client: supabase })))).flatMap((entry) => entry ? [entry.reveal] : []) : [];
  const same = reveals.filter((reveal) => reveal.own.move[0] === reveal.partner.move[0]).length;
  return <main className="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6 sm:py-10"><Link href={`/teams/${encodeURIComponent(teamId)}/collaboration-lab/founder-in-the-wild`} className="text-sm font-medium text-slate-600 underline-offset-4 hover:underline focus-visible:ring-2 focus-visible:ring-violet-500">{t("back")}</Link>
    <header className="mt-6 rounded-[30px] border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-amber-50 p-6 sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-700">{t("eyebrow")}</p><h1 className="mt-3 text-3xl font-semibold">{t("title")}</h1><p className="mt-3 text-sm leading-7 text-slate-700">{t("intro")}</p><p className="mt-3 text-sm font-medium text-violet-800">{t("progress", { current: round.openedPromptPositions.length, total: round.prompts.length })}</p></header>
    <section className="mt-6 divide-y divide-slate-200 border-y border-slate-200">{round.prompts.map((prompt) => { const opened = round.openedPromptPositions.includes(prompt.position); return <article key={prompt.roundPromptId} className="flex flex-col gap-3 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{opened ? t("view") : t("sealed")}</p><h2 className="mt-1 text-lg font-semibold">{prompt.content.title[locale]}</h2></div>{opened ? <Link href={`${roundPath}/reveal/${prompt.position}`} className="inline-flex min-h-11 items-center text-sm font-semibold text-violet-800 underline-offset-4 hover:underline">{t("view")}</Link> : <form action={openFounderInTheWildRevealAction.bind(null, teamId, roundId, prompt.position)}><button className="min-h-11 rounded-xl border border-violet-300 px-4 py-2 text-sm font-semibold text-violet-900 focus-visible:ring-2 focus-visible:ring-violet-500">{t("open")}</button></form>}</article>; })}</section>
    {allOpened && reveals.length === 5 ? <section className="mt-8 rounded-[28px] border border-amber-200 bg-amber-50/50 p-6 sm:p-8"><h2 className="text-2xl font-semibold">{t("debriefTitle")}</h2><p className="mt-3 text-sm leading-7 text-slate-700">{t("debriefIntro", { same, different: 5 - same })}</p>{round.status === "active" ? <form action={completeFounderInTheWildRoundAction.bind(null, teamId, roundId)} className="mt-6"><button className="min-h-11 rounded-xl bg-violet-700 px-5 py-3 text-sm font-semibold text-white">{t("complete")}</button></form> : <p className="mt-6 text-sm font-semibold text-violet-800">{t("completed")}</p>}{query.result === "waiting" ? <p role="status" className="mt-3 text-sm text-slate-600">{t("waiting", { name: partnerName })}</p> : null}</section> : null}
  </main>;
}
