import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getLocale, getTranslations } from "next-intl/server";
import { ReadMyMindEndControl } from "@/features/collaborationLab/ReadMyMindEndControl";
import { FounderInTheWildPromptForm } from "@/features/founderInTheWild/FounderInTheWildPromptForm";
import { declineFounderInTheWildRoundAction, discardFounderInTheWildRoundAction, lockFounderInTheWildScenarioAction } from "@/features/founderInTheWild/founderInTheWildActions";
import { getFounderInTheWildRound, getFounderInTheWildTeam } from "@/features/founderInTheWild/founderInTheWildData";
import { normalizeLocale } from "@/i18n/config";
import { createClient } from "@/lib/supabase/server";

export default async function FounderInTheWildRoundPage({ params, searchParams }: { params: Promise<{ teamId: string; roundId: string }>; searchParams: Promise<{ intro?: string; result?: string }> }) {
  const [{ teamId, roundId }, query] = await Promise.all([params, searchParams]); const href = `/teams/${encodeURIComponent(teamId)}/collaboration-lab/founder-in-the-wild/${encodeURIComponent(roundId)}`;
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect(`/login?next=${encodeURIComponent(href)}`);
  const team = await getFounderInTheWildTeam(teamId, user.id, supabase); if (!team) notFound(); const round = await getFounderInTheWildRound(team, roundId, user.id, supabase); if (!round) notFound();
  const [t, rawLocale] = await Promise.all([getTranslations("founderInTheWild.round"), getLocale()]); const locale = normalizeLocale(rawLocale); const partnerName = round.partner.displayName ?? (locale === "de" ? "dein Co-Founder" : "your co-founder");
  const back = <Link href={`/teams/${encodeURIComponent(teamId)}/collaboration-lab/founder-in-the-wild`} className="text-sm font-medium text-slate-600 underline-offset-4 hover:underline focus-visible:ring-2 focus-visible:ring-violet-500">{t("back")}</Link>;
  const endControl = round.canDiscard ? <ReadMyMindEndControl action={discardFounderInTheWildRoundAction.bind(null, teamId, roundId)} label={t("discard")} title={t("discardTitle")} confirmation={t("discardConfirm")} cancel={t("cancel")} variant="danger" /> : round.canDecline ? <ReadMyMindEndControl action={declineFounderInTheWildRoundAction.bind(null, teamId, roundId)} label={t("decline")} title={t("declineTitle")} confirmation={t("declineConfirm")} cancel={t("cancel")} /> : null;
  const shell = (content: React.ReactNode) => <main className="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6 sm:py-10">{back}{query.result ? <p role="alert" className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-950">{t(query.result === "invalid" ? "invalid" : "changed")}</p> : null}{content}</main>;
  if (round.wholeRoundAnswerComplete) return shell(<section className="mt-6 rounded-[28px] border border-violet-200 bg-gradient-to-br from-violet-50 to-amber-50 p-6 sm:p-8"><h1 className="text-2xl font-semibold">{t("revealTitle")}</h1><p className="mt-3 text-sm leading-7 text-slate-700">{t("revealText")}</p><Link href={`${href}/reveal`} className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-violet-700 px-5 py-3 text-sm font-semibold text-white">{t("revealAction")}</Link></section>);
  if (round.ownAnswerComplete) return shell(<section className="mt-6 rounded-[28px] border border-slate-200 bg-white p-6 sm:p-8"><h1 className="text-2xl font-semibold">{t("waitingTitle")}</h1><p className="mt-3 text-sm leading-7 text-slate-700">{t("waitingText", { name: partnerName })}</p><p className="mt-2 text-sm text-slate-500">{t("waitingPrivacy")}</p>{endControl ? <div className="mt-6 border-t border-slate-200 pt-5">{endControl}</div> : null}</section>);
  if (round.prompts.every((prompt) => !prompt.complete) && query.intro !== "done") return shell(<section className="mt-6 rounded-[30px] border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-amber-50 p-6 sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-700">{t("eyebrow")}</p><h1 className="mt-3 text-3xl font-semibold">{t("introTitle")}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-700">{t("introBody")}</p><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-700">{t("introReflection")}</p><div className="mt-6 flex flex-wrap items-center gap-3"><Link href={`${href}?intro=done`} className="inline-flex min-h-11 items-center rounded-xl bg-violet-700 px-5 py-3 text-sm font-semibold text-white">{t("introAction")}</Link>{endControl}</div></section>);
  const prompt = round.prompts.find((entry) => entry.position === round.nextPromptPosition); if (!prompt) return shell(null);
  return shell(<><header className="mt-6 rounded-[30px] border border-amber-200/80 bg-gradient-to-br from-amber-50 via-white to-violet-50 p-6 sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-700">{t("scene", { current: prompt.position + 1, total: round.prompts.length })}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">{prompt.content.title[locale]}</h1><p className="mt-4 text-lg leading-8 text-slate-700">{prompt.content.situation[locale]}</p><p className="mt-5 text-xl font-semibold text-slate-950">{prompt.content.question[locale]}</p></header><FounderInTheWildPromptForm prompt={prompt} locale={locale} action={lockFounderInTheWildScenarioAction.bind(null, teamId, roundId, prompt.roundPromptId)} labels={{ move: t("move"), matters: t("matters"), mattersHint: t("mattersHint"), need: t("need"), lock: t("lock"), locking: t("locking"), warning: t("warning") }}/>{endControl ? <div className="mt-6 border-t border-slate-200 pt-5">{endControl}</div> : null}</>);
}
