import { getTranslations } from "next-intl/server"; import { requireNetworkMember } from "@/features/network/networkAccess"; import { getOwnNetworkProfile } from "@/features/network/networkData"; import { reuseExistingProfileAction, saveNetworkProfileAction } from "@/features/network/networkActions"; import { NETWORK_REMOTE_MODES, NETWORK_ROLES } from "@/features/network/networkTypes";
const field = "mt-2 min-h-11 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:ring-4 focus:ring-slate-100";
export default async function NetworkProfilePage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) { const t = await getTranslations("network"); const { client,user } = await requireNetworkMember("/network/profile"); const [profile,params] = await Promise.all([getOwnNetworkProfile(client,user.id),searchParams]); return <main className="mx-auto max-w-4xl px-5 py-10"><p className="text-xs uppercase tracking-[.18em] text-slate-500">{t("eyebrow")}</p><h1 className="mt-2 text-3xl font-semibold">{t("profile.title")}</h1><p className="mt-2 max-w-2xl text-slate-600">{t("profile.text")}</p>
 {!profile ? <form action={reuseExistingProfileAction} className="mt-6 rounded-2xl border border-cyan-200 bg-cyan-50 p-5"><p className="text-sm text-slate-700">{t("profile.reuseText")}</p><button className="mt-3 min-h-11 rounded-full border border-cyan-300 bg-white px-5 text-sm font-semibold">{t("profile.reuse")}</button></form> : null}
 {params.reused ? <p className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-900">{t("profile.reused")}</p> : null}{params.error ? <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">{t(`errors.${params.error}`)}</p> : null}
 <form action={saveNetworkProfileAction} className="mt-6 space-y-6 rounded-3xl border border-slate-200 bg-white p-6">
  <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">{t("profile.name")}<input required maxLength={80} name="display_name" defaultValue={profile?.display_name} className={field}/></label><label className="text-sm font-medium">{t("profile.headline")}<input required maxLength={160} name="headline" defaultValue={profile?.headline} className={field}/></label></div>
  <label className="block text-sm font-medium">{t("profile.bio")}<textarea required minLength={20} maxLength={800} rows={5} name="bio" defaultValue={profile?.bio} className={field}/></label>
  <fieldset><legend className="text-sm font-medium">{t("profile.roles")}</legend><p className="mt-1 text-xs text-slate-500">{t("profile.rolesHint")}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{NETWORK_ROLES.map((role) => <label key={role} className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 px-3 text-sm"><input type="checkbox" name="network_roles" value={role} defaultChecked={profile?.network_roles.includes(role)}/>{t(`roles.${role}`)}</label>)}</div></fieldset>
  <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">{t("profile.expertise")}<input name="expertise" defaultValue={profile?.expertise.join(", ")} className={field}/></label><label className="text-sm font-medium">{t("profile.industries")}<input name="industries" defaultValue={profile?.industries.join(", ")} className={field}/></label><label className="text-sm font-medium">{t("profile.location")}<input name="location_region" maxLength={120} defaultValue={profile?.location_region || ""} className={field}/></label><label className="text-sm font-medium">{t("profile.remote")}<select name="remote_mode" defaultValue={profile?.remote_mode || ""} className={field}><option value="">{t("form.optional")}</option>{NETWORK_REMOTE_MODES.map((v) => <option key={v} value={v}>{t(`remote.${v}`)}</option>)}</select></label></div>
  <p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">{t("profile.consent")}</p><div className="flex flex-wrap gap-3"><button name="intent" value="publish" className="min-h-11 rounded-full bg-[color:var(--brand-primary)] px-5 text-sm font-semibold">{t("profile.publish")}</button><button name="intent" value="draft" className="min-h-11 rounded-full border border-slate-200 px-5 text-sm font-semibold">{t("actions.saveDraft")}</button></div>
 </form></main>; }
