export const DAILY_QUOTES: string[] = [
  "Tempo schlägt Perfektion, solange du lernst.",
  "Ein klares Nein spart dir zehn halbherzige Jas.",
  "Cashflow ist kein Detail, sondern Sauerstoff.",
  "Wenn alles Priorität hat, hat nichts Priorität.",
  "Strategie ist, was du bewusst nicht tust.",
  "Gute Co-Founder ergänzen, sie duplizieren nicht.",
  "Entscheidungen werden leichter mit klaren Kriterien.",
  "Schlechte Meetings sind teure Gewohnheiten.",
  "Hypothesen zuerst, Meinungen später.",
  "Traktion schlägt Decks, fast immer.",
  "Komplexität wächst von allein, Einfachheit ist Arbeit.",
  "Ein MVP ist ein Start, kein Urteil.",
  "Klare Rollen reduzieren stille Konflikte.",
  "Timing hilft, aber Fokus gewinnt öfter.",
  "Ein guter Prozess ist skalierbares Vertrauen.",
  "Nicht jede Chance ist eine Aufgabe für euch.",
  "Feedback ist nur wertvoll, wenn es konkret wird.",
  "Wachstum ohne Richtung ist nur Bewegung.",
  "Konsistenz wirkt unspektakulär und schlägt trotzdem.",
  "Der Markt belohnt Nutzen, nicht Buzzwords.",
  "Roadmaps sind Hypothesen mit Datum.",
  "Mut ist auch, einen Plan rechtzeitig zu ändern.",
  "Produktivität beginnt oft mit weniger Kontextwechsel.",
  "Verantwortung wird klarer, wenn Ownership sichtbar ist.",
  "Ein guter Pitch beantwortet ein echtes Risiko.",
  "Kosten sinken selten durch Hoffnung.",
  "Klare Kommunikation spart spätere Reparaturarbeit.",
  "Schnelle Experimente brauchen saubere Auswertung.",
  "Streit ist okay, Unklarheit ist teuer.",
  "Fortschritt ist oft eine Serie kleiner Korrekturen.",
];
