-- Generated from the frozen Phase 8.4-v0.2 source; never overwrite historical item versions.
begin;
insert into public.workstyle_item_versions(instrument_id,assessment_version,item_key,item_version,position,definition)
select 'founder-workstyle-pretest-8-5a-v1',item->>'assessment_version',item->>'item_key',item->>'item_version',position::integer,item
from jsonb_array_elements($workstyle$[
  {
    "item_key": "EVI-01",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Evidenzorientierung",
    "facet": "Prüfen",
    "facet_status": "development_mapping",
    "prompt": "Du hast mehrere realistische Möglichkeiten vor dir. Wie oft vergleichst du ihre Vor- und Nachteile, bevor du dich festlegst?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "live_reference",
    "source_status": "live_reference",
    "source_status_explicit": true,
    "source_note": "bestehendes Live-Item / UX-Referenz",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-02",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Evidenzorientierung",
    "facet": "Prüfen",
    "facet_status": "development_mapping",
    "prompt": "Eine wichtige Entscheidung hängt davon ab, ob eine Annahme stimmt. Wie oft prüfst du gezielt, was dafür oder dagegen spricht?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "live_reference",
    "source_status": "live_reference",
    "source_status_explicit": true,
    "source_note": "bestehendes Live-Item / UX-Referenz",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-03",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Evidenzorientierung",
    "facet": "Prüfen",
    "facet_status": "development_mapping",
    "prompt": "Du hast eine klare Lieblingsoption. Wie oft suchst du gezielt nach Informationen, die gegen sie sprechen könnten?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "A",
    "note": null
  },
  {
    "item_key": "EVI-04",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Evidenzorientierung",
    "facet": "Prüfen",
    "facet_status": "development_mapping",
    "prompt": "Wie oft fragst du dich vor einer wichtigen Entscheidung, welche zusätzliche Information deine Einschätzung noch verändern würde?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "aus älterem Material weiterentwickelt",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "B",
    "note": null
  },
  {
    "item_key": "EVI-05",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Evidenzorientierung",
    "facet": "Revidieren",
    "facet_status": "development_mapping",
    "prompt": "Neue Informationen sprechen deutlich gegen eine Richtung, auf die du dich schon festgelegt hast. Wie oft prüfst du die Entscheidung neu?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-06",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Evidenzorientierung",
    "facet": "Revidieren",
    "facet_status": "development_mapping",
    "prompt": "Ein Ergebnis widerspricht deiner bisherigen Einschätzung. Wie oft gehst du der Abweichung nach, bevor du sie als Ausnahme abhakst?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "C",
    "note": null
  },
  {
    "item_key": "EVI-07",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Evidenzorientierung",
    "facet": "Revidieren",
    "facet_status": "development_mapping",
    "prompt": "Du hast bereits viel Zeit in einen Weg investiert. Wie oft ziehst du trotzdem eine andere Richtung ernsthaft in Betracht, wenn neue Informationen dafür sprechen?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EXP-01",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du kennst dich mit einem Thema gut aus. Wie viel Gewicht hat dein erster Eindruck bei deiner Entscheidung?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "live_reference",
    "source_status": "live_reference",
    "source_status_explicit": true,
    "source_note": "bestehendes Live-Item / UX-Referenz",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": "Im Pretest ausdrücklich darauf achten, ob „erster Eindruck“ tatsächlich erfahrungsbasierte Mustererkennung oder bloßen Affekt/Impuls auslöst."
  },
  {
    "item_key": "EXP-02",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Mehrere Möglichkeiten schneiden anhand der verfügbaren Fakten ähnlich gut ab. Wie viel Gewicht gibst du deiner Erfahrung aus vergleichbaren Situationen?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "aus älterem I05-Thema weiterentwickelt",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EXP-03",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Dir fällt in einer vertrauten Situation sofort ein Muster auf. Wie stark berücksichtigst du diesen Eindruck bei deiner weiteren Einschätzung?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "A",
    "note": null
  },
  {
    "item_key": "EXP-04",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Eine Option sieht auf dem Papier gut aus, passt aber nicht zu dem, was du aus ähnlichen Situationen kennst. Wie stark fließt diese Erfahrung in deine Entscheidung ein?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "B",
    "note": null
  },
  {
    "item_key": "EXP-05",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du kannst einen ersten Eindruck noch nicht vollständig erklären, erkennst die Situation aber aus früheren Erfahrungen wieder. Wie viel Gewicht gibst du diesem Signal?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "C",
    "note": null
  },
  {
    "item_key": "EXP-06",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Daten und deine Erfahrung weisen in unterschiedliche Richtungen. Wie stark beziehst du deine Erfahrung als zusätzliche Informationsquelle ein?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-01",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Wie oft beantwortest du eine offene Frage durch einen kleinen praktischen Versuch?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "aus älterem E07-Thema weiterentwickelt",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-02",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Wenn zwei Wege plausibel sind, wie oft testest du sie zunächst in kleinem Rahmen, bevor du dich festlegst?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-03",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Wie oft klärst du vor einem Versuch, was du dadurch eigentlich herausfinden möchtest?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "A",
    "note": null
  },
  {
    "item_key": "EL-04",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Wie oft wertest du nach einem Versuch bewusst aus, was das Ergebnis für die nächste Entscheidung bedeutet?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-05",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Wenn ein erster Versuch keine klare Antwort liefert: Wie oft veränderst du ihn gezielt und testest erneut?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "B",
    "note": null
  },
  {
    "item_key": "VOICE-01",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Timing",
    "facet_status": "development_mapping",
    "prompt": "Wenn dir bei einer gemeinsamen Entscheidung ein relevanter Einwand auffällt, wie oft sprichst du ihn an, bevor endgültig entschieden ist?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": false,
    "source_note": "keine individuelle Herkunftsangabe in der Quelle",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-02",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Sichtbarkeit",
    "facet_status": "development_mapping",
    "prompt": "Du merkst früh, dass du eine andere Sicht hast, kannst sie aber noch nicht vollständig begründen. Wie oft machst du trotzdem sichtbar, dass du einen Klärungspunkt siehst?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": false,
    "source_note": "keine individuelle Herkunftsangabe in der Quelle",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "A",
    "note": null
  },
  {
    "item_key": "VOICE-03",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Explizitheit",
    "facet_status": "development_mapping",
    "prompt": "Wie häufig sagst du ausdrücklich, dass du einer Entscheidung nicht zustimmst, wenn das tatsächlich der Fall ist?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": false,
    "source_note": "keine individuelle Herkunftsangabe in der Quelle",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-04",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Sichtbarkeit",
    "facet_status": "development_mapping",
    "prompt": "Eine unangenehme Information ist für andere im Team relevant. Wie häufig machst du sie sichtbar, sobald du ihre Bedeutung erkannt hast?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": false,
    "source_note": "keine individuelle Herkunftsangabe in der Quelle",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "B",
    "note": null
  },
  {
    "item_key": "VOICE-05",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Timing",
    "facet_status": "development_mapping",
    "prompt": "Ein wichtiges Konfliktthema wurde zunächst vertagt. Wie häufig bringst du es später wieder auf, wenn es noch nicht geklärt ist?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": false,
    "source_note": "keine individuelle Herkunftsangabe in der Quelle",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-06",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Explizitheit",
    "facet_status": "development_mapping",
    "prompt": "Wenn du eine Änderung für notwendig hältst: Wie häufig machst du konkret, was du anders haben möchtest?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": false,
    "source_note": "keine individuelle Herkunftsangabe in der Quelle",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "C",
    "note": null
  },
  {
    "item_key": "AMB-01",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Für ein Ergebnis gibt es mehrere plausible Erklärungen – und noch ist unklar, welche davon zutrifft.",
    "stem": "Wie wohl fühlst du dich jeweils in dieser Situation?",
    "response_format": "ambiguity_comfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "live_reference",
    "source_status": "live_reference",
    "source_status_explicit": true,
    "source_note": "bestehendes Live-Thema",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-02",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Über mehrere Wochen bleibt offen, welche von zwei Richtungen euer Vorhaben nehmen wird.",
    "stem": "Wie wohl fühlst du dich jeweils in dieser Situation?",
    "response_format": "ambiguity_comfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "live_reference",
    "source_status": "live_reference",
    "source_status_explicit": true,
    "source_note": "bestehendes Live-Item / Research-Kandidat wegen möglicher starker Venture-Kontextabhängigkeit",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "A",
    "note": null
  },
  {
    "item_key": "AMB-03",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Ihr bekommt zu derselben Idee widersprüchliche Rückmeldungen – und noch ist unklar, welche davon relevanter sind.",
    "stem": "Wie wohl fühlst du dich jeweils in dieser Situation?",
    "response_format": "ambiguity_comfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "live_reference",
    "source_status": "live_reference",
    "source_status_explicit": true,
    "source_note": "bestehendes Live-Item",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-04",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Eine wichtige Frage bleibt eine Zeit lang ohne eindeutige Antwort.",
    "stem": "Wie wohl fühlst du dich jeweils in dieser Situation?",
    "response_format": "ambiguity_comfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "live_reference",
    "source_status": "live_reference",
    "source_status_explicit": true,
    "source_note": "bestehendes Live-Item",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-05",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Für eine wichtige Entwicklung sind mehrere Ausgänge plausibel und keiner lässt sich derzeit zuverlässig vorhersagen.",
    "stem": "Wie wohl fühlst du dich jeweils in dieser Situation?",
    "response_format": "ambiguity_comfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "B",
    "note": null
  },
  {
    "item_key": "AMB-06",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du arbeitest an einem Thema weiter, obwohl sich noch keine eindeutig beste Vorgehensweise erkennen lässt.",
    "stem": "Wie wohl fühlst du dich jeweils in dieser Situation?",
    "response_format": "ambiguity_comfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "C",
    "note": null
  },
  {
    "item_key": "ORG-01",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Struktur & Priorisierung",
    "facet_status": "source_defined",
    "prompt": "Bevor du ein größeres Vorhaben startest: Wie oft legst du konkrete nächste Schritte oder Zwischenziele fest?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "aus älterem EX07-Thema weiterentwickelt",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-02",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Struktur & Priorisierung",
    "facet_status": "source_defined",
    "prompt": "Wenn mehrere wichtige Aufgaben gleichzeitig anstehen: Wie oft entscheidest du bewusst, was zuerst dran ist?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-03",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Struktur & Priorisierung",
    "facet_status": "source_defined",
    "prompt": "Wenn sich Prioritäten verändern: Wie oft ordnest du deine nächsten Schritte neu, statt die neuen Aufgaben einfach zusätzlich aufzunehmen?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "A",
    "note": null
  },
  {
    "item_key": "ORG-04",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Struktur & Priorisierung",
    "facet_status": "source_defined",
    "prompt": "Wenn du etwas zugesagt hast: Wie oft behältst du selbst im Blick, ob es zum vereinbarten Zeitpunkt erledigt wird?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-05",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Selbstmonitoring & Belastungssteuerung",
    "facet_status": "source_defined",
    "prompt": "Wenn eine Aufgabe ins Stocken gerät: Wie oft bemerkst du das früh genug, um dein Vorgehen noch anzupassen?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "B",
    "note": null
  },
  {
    "item_key": "ORG-06",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Selbstmonitoring & Belastungssteuerung",
    "facet_status": "source_defined",
    "prompt": "Wenn deine Arbeitslast dauerhaft zu hoch wird: Wie oft priorisierst oder reduzierst du Aufgaben bewusst neu?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-07",
    "item_version": "8.4-v0.2",
    "assessment_version": "8.5a-v1",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Selbstmonitoring & Belastungssteuerung",
    "facet_status": "source_defined",
    "prompt": "Wenn du merkst, dass deine Konzentration oder Leistungsfähigkeit deutlich nachlässt: Wie oft passt du deine Arbeitsweise an?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "neu",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": "C",
    "note": null
  }
]$workstyle$::jsonb) with ordinality as items(item,position);
commit;
