-- Generated from Phase 8.4-v0.3. Additive only; v0.2 stays immutable.
begin;
insert into public.workstyle_item_versions(instrument_id,assessment_version,item_key,item_version,position,definition)
select 'founder-workstyle-pretest-8-5a-v2',item->>'assessment_version',item->>'item_key',item->>'item_version',position::integer,item
from jsonb_array_elements($workstyle$[
  {
    "item_key": "ORG-01",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Struktur / Priorisierung",
    "facet_status": "development_mapping",
    "prompt": "Bei einem größeren Vorhaben: Wie häufig klärst du für dich zuerst die nächsten Schritte, bevor du richtig loslegst?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EXP-01",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du kennst dich mit einem Thema gut aus und hast ziemlich schnell ein Gefühl dafür, was funktionieren könnte. Wie stark fließt dieser erste Eindruck in deine weitere Einschätzung ein?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-01",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Timing",
    "facet_status": "development_mapping",
    "prompt": "Ihr seid mit einer Entscheidung fast durch. Dir fällt aber noch ein Haken auf. Wie wahrscheinlich ist es, dass du ihn noch ansprichst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-01",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Es gibt mehrere plausible Erklärungen, aber im Moment lässt sich nicht klären, welche stimmt. Wie unangenehm ist das für dich?",
    "stem": null,
    "response_format": "ambiguity_discomfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-01",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Eine offene Frage ließe sich mit einem kleinen Versuch klären. Wie häufig probierst du das tatsächlich aus?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-01",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Evidenzorientierung",
    "facet": "Prüfen",
    "facet_status": "development_mapping",
    "prompt": "Du hast mehrere Möglichkeiten, die alle infrage kommen. Wie häufig vergleichst du sie genauer, bevor du dich entscheidest?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-02",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du musst an einem Thema weiterarbeiten, obwohl eine wichtige Frage erst einmal offenbleibt. Wie unangenehm ist das für dich?",
    "stem": null,
    "response_format": "ambiguity_discomfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-02",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Evidenzorientierung",
    "facet": "Prüfen",
    "facet_status": "development_mapping",
    "prompt": "Eine wichtige Entscheidung hängt davon ab, ob eine bestimmte Annahme stimmt. Wie häufig prüfst du gezielt, was dafür und was dagegen spricht?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-R1",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Struktur / Priorisierung",
    "facet_status": "development_mapping",
    "prompt": "Du hast dir für den Tag einiges vorgenommen. Mittags merkst du, dass du deutlich weniger geschafft hast als geplant. Wie wahrscheinlich ist es, dass du den Rest des Tages neu sortierst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "Neues Mikroszenario im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-02",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Zwei Wege könnten funktionieren. Wie häufig probierst du erst einmal einen kleinen Teil aus, bevor du dich festlegst?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EXP-02",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Zwei Möglichkeiten sehen nach den verfügbaren Informationen ungefähr gleich gut aus. Wie stark beziehst du dann deine Erfahrung aus ähnlichen Situationen mit ein?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-02",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Sichtbarkeit",
    "facet_status": "development_mapping",
    "prompt": "In einem Gespräch merkst du, dass du die Sache anders siehst. Du kannst aber noch nicht genau sagen, warum. Wie wahrscheinlich ist es, dass du trotzdem sagst, dass du noch einen Punkt siehst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-R1",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Timing",
    "facet_status": "development_mapping",
    "prompt": "Das Gespräch ist eigentlich schon beim nächsten Thema. Dir fällt aber auf, dass bei der letzten Entscheidung etwas Wichtiges fehlt. Wie wahrscheinlich ist es, dass du das noch einmal ansprichst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "Neues Mikroszenario im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": null,
    "note": null
  },
  {
    "item_key": "EXP-03",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Eine Situation kommt dir bekannt vor und du erkennst ein Muster, das du schon einmal erlebt hast. Wie stark beeinflusst das deine Einschätzung?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-03",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Evidenzorientierung",
    "facet": "Prüfen",
    "facet_status": "development_mapping",
    "prompt": "Du hast eigentlich schon einen Favoriten. Wie häufig schaust du trotzdem noch gezielt nach Gründen, die dagegen sprechen?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-02",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Struktur / Priorisierung",
    "facet_status": "development_mapping",
    "prompt": "Mehrere wichtige Dinge brauchen gleichzeitig deine Aufmerksamkeit. Wie häufig sortierst du neu, was jetzt Vorrang hat?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-03",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du bekommst zu derselben Idee widersprüchliche Rückmeldungen und kannst noch nicht erkennen, welche davon wichtiger ist. Wie unangenehm ist das für dich?",
    "stem": null,
    "response_format": "ambiguity_discomfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-03",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Bevor du etwas ausprobierst: Wie häufig ist für dich klar, was du damit eigentlich herausfinden möchtest?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-R1",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du weißt nicht, welche von zwei Ideen bei potenziellen Nutzer:innen besser ankommt. Beide könntest du schnell in einer einfachen Version zeigen. Wie wahrscheinlich ist es, dass du daraus einen kleinen Test machst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "Neues Mikroszenario im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-04",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Bei einer wichtigen Entwicklung sind mehrere Ausgänge möglich und gerade lässt sich keiner zuverlässig vorhersagen. Wie unangenehm ist das für dich?",
    "stem": null,
    "response_format": "ambiguity_discomfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-03",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Explizitheit",
    "facet_status": "development_mapping",
    "prompt": "Eine Entscheidung wird getroffen, mit der du wirklich nicht einverstanden bist. Wie wahrscheinlich ist es, dass du das auch klar sagst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-04",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Evidenzorientierung",
    "facet": "Revidieren",
    "facet_status": "development_mapping",
    "prompt": "Du hast dich entschieden. Später bekommst du neue Informationen, die deutlich dagegen sprechen. Wie häufig stellst du deine Entscheidung dann noch einmal infrage?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-03",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Struktur / Priorisierung",
    "facet_status": "development_mapping",
    "prompt": "Du hast deinen Tag oder deine Woche geplant und plötzlich ändern sich die Prioritäten. Wie häufig stellst du deinen Plan darauf um?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EXP-04",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Auf dem Papier sieht eine Möglichkeit gut aus. Aus ähnlichen Situationen kennst du aber Dinge, die dich daran zweifeln lassen. Wie stark beeinflusst diese Erfahrung deine Entscheidung?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EXP-R1",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du vergleichst zwei Anbieter. Preis und Leistung sind ähnlich. Mit einer vergleichbaren Lösung hast du schon einmal gute oder schlechte Erfahrungen gemacht. Wie stark beeinflusst das deine Entscheidung?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "Neues Mikroszenario im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-04",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Umsetzen / Nachhalten",
    "facet_status": "development_mapping",
    "prompt": "Du hast zugesagt, etwas bis zu einem bestimmten Zeitpunkt zu erledigen. Wie häufig prüfst du zwischendurch, ob du damit noch im Plan bist?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-04",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du hast etwas ausprobiert und bekommst ein Ergebnis. Wie häufig leitest du daraus bewusst ab, was du als Nächstes machst?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-04",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Sichtbarkeit",
    "facet_status": "development_mapping",
    "prompt": "Du erfährst etwas Unangenehmes, das für eure gemeinsame Arbeit wichtig ist. Wie wahrscheinlich ist es, dass du es zeitnah ansprichst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-05",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Evidenzorientierung",
    "facet": "Revidieren",
    "facet_status": "development_mapping",
    "prompt": "Etwas läuft ganz anders als erwartet. Wie häufig versuchst du herauszufinden, woran es gelegen hat?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-05",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Mehrere Wege könnten funktionieren, aber keiner ist eindeutig der beste. Trotzdem musst du weitermachen. Wie unangenehm ist das für dich?",
    "stem": null,
    "response_format": "ambiguity_discomfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EVI-R1",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Evidenzorientierung",
    "facet": "Revidieren",
    "facet_status": "development_mapping",
    "prompt": "Ihr arbeitet schon eine Weile mit Lösung A. Dann tauchen neue Informationen auf, die deutlich für Lösung B sprechen. Wie wahrscheinlich ist es, dass du einen Wechsel noch einmal ernsthaft prüfst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "Neues Mikroszenario im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": null,
    "note": null
  },
  {
    "item_key": "AMB-R1",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Ambiguitätstoleranz",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Du musst die nächsten Schritte planen, obwohl sich zwei wichtige Rahmenbedingungen wahrscheinlich noch ändern werden. Wie unangenehm ist das für dich?",
    "stem": null,
    "response_format": "ambiguity_discomfort",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "new",
    "source_status": "new",
    "source_status_explicit": true,
    "source_note": "Neues Mikroszenario im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "research_only",
    "research_only": true,
    "product_status": "excluded",
    "form": null,
    "note": null
  },
  {
    "item_key": "ORG-05",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Arbeitsorganisation & Selbststeuerung",
    "facet": "Selbstmonitoring / Belastungssteuerung",
    "facet_status": "development_mapping",
    "prompt": "Über eine Weile kommt mehr zusammen, als du realistisch schaffen kannst. Wie häufig entscheidest du dann neu, was warten oder wegfallen kann?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "VOICE-05",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Konstruktive Voice / sachlicher Dissens",
    "facet": "Timing",
    "facet_status": "development_mapping",
    "prompt": "Ein schwieriges Thema wurde vertagt und danach nicht wieder aufgegriffen. Für dich ist es aber noch nicht erledigt. Wie wahrscheinlich ist es, dass du es wieder auf den Tisch bringst?",
    "stem": null,
    "response_format": "likelihood",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EL-05",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Experimentelles Lernen",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Ein erster Versuch bringt noch keine klare Antwort. Wie häufig veränderst du etwas und probierst es noch einmal?",
    "stem": null,
    "response_format": "frequency",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  },
  {
    "item_key": "EXP-05",
    "item_version": "8.4-v0.3",
    "assessment_version": "8.5a-v2",
    "construct": "Erfahrungsbasierte Urteilsnutzung",
    "facet": null,
    "facet_status": "not_specified",
    "prompt": "Bei einer Situation denkst du ziemlich schnell: „Das kenne ich.“ Du kannst aber noch nicht genau sagen, warum. Wie stark beeinflusst dieser Eindruck deine weitere Einschätzung?",
    "stem": null,
    "response_format": "experience_weight",
    "missing_reasons": [
      "cannot_assess"
    ],
    "source_type": "adapted",
    "source_status": "adapted",
    "source_status_explicit": true,
    "source_note": "Sprachliche Überarbeitung im fachlichen Review",
    "development_status": "candidate_for_pretest",
    "usage": "core",
    "research_only": false,
    "product_status": "pretest_comparison_candidate",
    "form": null,
    "note": null
  }
]$workstyle$::jsonb) with ordinality as items(item,position);
commit;
